### ISSUE TITLE
No "Take The Quiz Again" button for project 2

### ISSUE THREAD

**Issue by phildarnowsky** [susanBuck/e28-fall19#100]
I "took" the Project 2 quiz once just to have a look at the questions, and submitted it empty. Today I finished my actual project, but when I go to submit it, there's no "Take the quiz again" button for P2 like there is for normal quizzes.

**Comment by susanBuck** [comment]
Just enabled multiple attempts for P2. 
Let me know if you're still not seeing the option to take again.

**Comment by phildarnowsky** [comment]
Thanks!q
