### ISSUE TITLE
Weird happenings when trying to set a div's background-color ?!?!

### ISSUE THREAD

**Issue by gaderrick** [susanBuck/e28-fall19#101]
I'm running into an issue where this code:

```html
<div :class="{Match : correctGuess == true}">
  <p>{{ correctGuess }}</p>
</div>
```
is doing what it should (change the background color to green) in Safari, but it refuses to render in Chrome.

Any ideas?

**Comment by naztronaut** [comment]
Is the 'Match' class defined in your CSS? If it's new, Chrome maybe chrome cached an older version of the CSS and clearing it may help.

**Comment by gaderrick** [comment]
Ouch... when in doubt clear the cache. Thanks for the help you saved me pulling more hair out.

**Comment by gaderrick** [comment]
In case anyone else runs into the caching issue, I found this page (https://community.esri.com/thread/187211-how-to-force-a-browser-cache-refresh-after-updating-wab-app) that showed these three lines of code. It seems to do the trick with forcing the script.js to reload each time:

```html
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
<meta http-equiv="Pragma" content="no-cache" />
<meta http-equiv="Expires" content="0" />
```

**Comment by susanBuck** [comment]
Other tips to avoid being bit by the cache bug:

__Tip 1:__
Hold down "shift" in addition to your usual keyboard shortcut for refreshing. 
For example, on Mac I hold down "shift" + "cmd" + "r" to refresh - this forces a cache refresh. 
This works in Chrome - you may have to google around if using a different browser.

__Tip 2:__
Also in Chrome, you can configure your DevTools settings to automatically clear the cache if DevTools is open:
![image](https://user-images.githubusercontent.com/237711/67820986-c8f1c300-fa91-11e9-9299-8e1880748287.png)
