### ISSUE TITLE
Error trying to use custom local domain with Vue CLI 

### ISSUE THREAD

**Issue by terichadbourne** [susanBuck/e28-fall19#102]
I'm using Vue CLI for project 2 and can successfully get it running both on localhost (at localhost:8080) and on Digital Ocean. However, I hit an error while trying to follow [these instructions](https://hesweb.dev/e28/notes#/vue/build-comprehensive?jump=misc-custom-local-domains) for setting up a custom local domain. (Not clear if this is something we're actually required to do.)

Steps I've taken: 

Directly in my`p2` folder I added a file called `vue.config.js` with these contents: 

```javascript
module.exports = {
    devServer: {
        host: 'p2.loc'
    }
}
```

I used `nano` on my Mac to edit `/Applications/XAMPP/etc/extra/httpd-vhosts.conf` to add this: 
```
<VirtualHost *:80>
    ServerName p2.loc
    DocumentRoot /Applications/XAMPP/xamppfiles/htdocs/e28/p2
    <Directory /Applications/XAMPP/xamppfiles/htdocs/e28/p2>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Order allow,deny
        allow from all
    </Directory>
</VirtualHost>
```

(I've also tried it with `/dist` at the end of those filepaths, which didn't help.)

I restarted my server in XAMPP. 

I exited the process in Terminal that was running `npm run serve` to localhost:8000. 

I tried `npm run serve` again and got this error in the terminal: 
```
/Applications/XAMPP/xamppfiles/htdocs/e28/p2 (master)  $ npm run serve

> p2@0.1.0 serve /Applications/XAMPP/xamppfiles/htdocs/e28/p2
> vue-cli-service serve

 INFO  Starting development server...
10% building 2/2 modules 0 activeevents.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL 92.242.140.21:8080
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1334:19)
    at listenInCluster (net.js:1392:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1501:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! p2@0.1.0 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the p2@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/terichadbourne/.npm/_logs/2019-10-30T02_37_54_588Z-debug.log
```

If I delete `vue.config.js`, it goes back to working on `localhost:8080` and isn't upset by the settings added to `/Applications/XAMPP/etc/extra/httpd-vhosts.conf`. 

So I have two questions: 
- What am I doing wrong?
- Do I actually need to do it right? 😂

**Comment by extra808** [comment]
When you use `npm run serve`, XAMPP is not used to serve the pages, Node.js is. My guess is XAMPP is already running and a different Vhost configuration is already listening to port 80**8**0, the port `npm run serve` is trying to use.

Remember when you are going to have Apache as the web server, the DocumentRoot needs to be the /dist folder within your project (unless you customize there the build command's output goes).

**Comment by terichadbourne** [comment]
I've checked Terminal to ensure no other sites are running locally on `localhost:8080`, and I've stopped every server running in XAMPP, and neither of those actions seem to help. 

I don't understand why I'd use `/dist` for the version running on localhost since I've never done a build process locally, only on Digital Ocean. But regardless, I have already tried that and it didn't help. 

The instructions from @susanBuck in the VueCLI section say that "Once you set up week8spa.loc in your computer’s hosts file, you should now be able to access your site via http://week8spa.loc:8080 after running npm run serve."

Is "your computer's hosts file" something other than `/Applications/XAMPP/etc/extra/httpd-vhosts.conf`? If you're right @extra808 that XAMPP is completely uninvolved, I'm not sure why I'd be updating the host info in a file that lives in a XAMPP folder. ¯\_(ツ)_/¯

**Comment by naztronaut** [comment]
Your computer `hosts` file isn't the same as `vhosts.conf`. Check out the notes on that here: https://hesweb.dev/e28/notes#/local-server/local-domains?jump=step-3-create-a-new-host

Since you're running the app through `npm run serve`, you d on't need to involve XAMPP/Apache at all. Just need to make sure your computer knows that p2.loc is the same as your localhost because NPM/Vue is running its own web server to serve the app (if that makes sense).

**Comment by susanBuck** [comment]
+1 to @naztronaut's notes.

+ `/Applications/XAMPP/etc/extra/httpd-vhosts.conf` is an Apache config file, and should be irrelevant when serving the site using the nodejs/webpack dev server. 
+ You do need an entry in [your computer's hosts file](https://hesweb.dev/e28/notes#/local-server/local-domains?jump=step-3-create-a-new-host) (`/private/etc/hosts`) that directs traffic from `p2.loc` to your local server IP address (which is 127.0.0.1 regardless of whether you're using Apache/XAMPP or nodejs/webpack dev server). 

FYI Teri - regarding your original question - setting up local domains when using the nodejs/webpack dever is in fact optional : )

**Comment by susanBuck** [comment]
Note - showed an example of this for reference in the Week 9 videos.

Going to close this thread out now, but feel free to re-open or start a new thread if you're still having problems with this @terichadbourne.
