### ISSUE TITLE
Parsing error: invalid-first-character-of-tag-name (vue/no-parsing-error)

### ISSUE THREAD

**Issue by terichadbourne** [susanBuck/e28-fall19#104]
I have an odd error while using Vue CLI that I didn't have while using the same code with plain old Vue for Project 1. 

I had been checking the length of my solution (for a mystery word game) and using it to print to the screen whether it was an easy or hard game, like so: 

```js
<p>Level: {{solution.length < 6 ? 'Easy' : 'Hard'}}</p>
```

But in Vue CLI it gives me this error: 
`Parsing error: invalid-first-character-of-tag-name (vue/no-parsing-error)`
The arrow is pointing to the blank space before the 6 as shown below, and I have no idea why it's talking about tag names. 

![image](https://user-images.githubusercontent.com/19171465/67879092-c1263300-fb12-11e9-9de3-dd4a97bd4122.png)

I tried wrapping the conditional like this, but it didn't help: 
```js
<p>Level: {{(solution.length < 6) ? 'Easy' : 'Hard'}}</p>
```
Elsewhere in my code I use this computed property for another purpose: 
```js
easySolutions: function () {
      return this.solutions.filter(word => word.length < 6)
    },
```

I can remove the parsing error by changing my code to: 
```js
<p>Level: {{easySolutions.includes(solution) ? 'Easy' : 'Hard'}}</p>
```
but I don't understand what was wrong with the way I first had it. 

Anyone know how exactly I was making the linter mad at me?

**Comment by conc2304** [comment]
I found this thread based on your error, looks like you may need to change the configs on the linter

```This is a correct error as according to HTML spec:

invalid-first-character-of-tag-name error.
Tag open state's Anything else step.
To make valid HTML, you should use &lt; instead of the <.
Or you can ignore the error by the option of vue/no-parsing-error rule: https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/no-parsing-error.md#wrench-options```

**Comment by susanBuck** [comment]
Interesting debate on that thread you found, @conc2304. : )

To summarize, it seems like @terichadbourne's options are:
1. Use the alternative approach your found (`easySolutions.includes(solution)`)
2. Disable the linter message 
3. Replace the `<` with `&lt;` (tested this, does work)

..and a 4th option I'll propose - creating a computed property to get the level, extracting the logic out of the template:

```js
computed: {
        getLevel: function() {
            return this.solution.length < 6 ? 'Easy' : 'Hard';
        }
    },
```

**Comment by terichadbourne** [comment]
Thanks, everyone!
