### ISSUE TITLE
Problem with single quotes being converted to double quotes

### ISSUE THREAD

**Issue by gaderrick** [susanBuck/e28-fall19#106]
I'm having an issue with VS Code with quotes- whenever I save a file (.vue for instance), it is replacing all my single quotes with double quotes. This in turn causes my javascript to be formatted incorrectly and not work. Looking at google, it seems like this is something to do with the "prettier" extension, but I'm nervous to change it. 

I don't recall having this issue in the last class/projects. What am I missing?

**Comment by audreychenjj-2019** [comment]
I just experienced similar issues while following along the week9 videos. I used to use only single quotes and let VS Code convert them into double quotes after saving but this caused issues when I had double quotes inside single quotes because VS Code only converted the outer layer quotes (single quotes in this situation) into double quotes.

Now I just change my habit. When I have quotes inside quotes, I use double quotes outside and single quotes inside. This solved my problem. 

This works for me:
```Javascript
"'./../assets/images/products/' + product.id + '.jpg'"
```

This doesn't work for me:
```Javascript
'"./../assets/images/products/" + product.id + ".jpg"'
```

**Comment by andmade** [comment]
You have to edit the extension preferences to prefer single quotes. If you got to Preferences and search for Prettier, you should see all the config options for the extension. One of them is for single quotes, set it to true.

**Comment by gaderrick** [comment]
I don't see where the Prettier extension is installed, but changing the quotes around seems to work for some reason. What specific setting did you set once you filtered for "Prettier?" All I see are options for changing the default formatter for different file types. Thanks for the quick replies!

**Comment by andmade** [comment]
Ugh, apparently Vetur handles its prettier separately. You'll have to edit the preferences.json with the prettier options instead. 

Use Ctrl+Shift+P to open the panel, then write settings and choose the one that says json instead of ui. In the resulting .json, add this:

`  "vetur.format.defaultFormatterOptions": {
    "prettier": {
      "singleQuote": true
    }
  }`

**Comment by andmade** [comment]
If you want to learn more about now Vetur uses Prettier, along with additional configuration options, here's more info:

**Comment by gaderrick** [comment]
So something is very strange here... what resulting json do you mean?

**Comment by andmade** [comment]
VS Code has its Settings in UI and JSON format. Some of the options can only be edited in the JSON file, thought they've now made the UI version the default (I switched mine back). I think you can search for Veter in the UI version and you can edit the settings.json from there. I believe there's also a fly out from the Preferences menu, but search through the command palette for Settings should also pop up the JSOM version. 

Once you get it open, it looks somewhat like this: 
https://vscode.readthedocs.io/en/latest/getstarted/settings/

(Though you may not have the left panel showing.) 

Add the previous json to the end of this file (or the right side if both pop up, you won't be able to edit the left side).

**Comment by gaderrick** [comment]
Yeah, something is weird with the mac version I think. Or at least I have a config off kilter.

Thanks for trying to help :)

**Comment by andmade** [comment]
Here's the version that used the new UI, it may have more specific macOS instructions: 

https://code.visualstudio.com/docs/getstarted/settings

**Comment by kreinholz** [comment]
I'm on Windows 10 and have the same issue with VS Code. I changed my Preferences > Settings > Preferences > Quote Style for both JavaScript and TypeScript from their default of "auto" to "single" within VS Code, and also edited C:\Documents and Settings\{My Name}\Application Data\Code\User\settings.json to add @andmade's suggested line:

```
    "vetur.format.defaultFormatterOptions": {
        "prettier": {
            "singleQuote": true
        }
    }
```
My outer single quotes are still being converted to double quotes in .vue files. I can live with it, although I'd prefer to work with outer single quotes and not have VS Code override what I input.

**Comment by andmade** [comment]
When I did it, it worked for changing all of the JavaScript to single parts, other parts of the code (all the template/HTML stuff) will remain as double quotes. 

Vetur apparently uses 3 different formatters. The one for HTML uses prettyhtml, which I guess is what is taking prescidence here. I'd try adding a "prettyhtml" key and add the single quote option to true there as well. I don't have my laptop on me to test right now, though.

**Comment by susanBuck** [comment]
For reference, here's what I have in my VSCode settings relating to vetur/single quotes:

```
"vetur.format.defaultFormatterOptions": {
        "prettier": {
            "singleQuote": true
        },
        "prettyhtml": {
            "singleQuote": true
        }
    },
```

**Comment by susanBuck** [comment]
For more details, see my reply in #107.

**Comment by terichadbourne** [comment]
Quick summary for anyone just joining the thread. Here's what worked for me to both find and apply the settings, as someone whose settings are currently in the UI version (as opposed to JSON): 

In VSCode, click the gear icon at lower left and select Settings (or in the menu go to Code > Preferences > Settings) to get to the UI version of your settings.

Scroll down until you see a link labelled "Edit in settings.json" (they're sprinkled throughout but all seem to go to the same place, so you don't need to find it in the Vetur section specifically). 
![image](https://user-images.githubusercontent.com/19171465/68341329-3e731a00-00b6-11ea-9bb4-44730d630001.png)

Add the code block suggested by Susan at the end of this file (highlighted below): 
![image](https://user-images.githubusercontent.com/19171465/68341395-5cd91580-00b6-11ea-97b8-ac9e681a05b6.png)

```js
,
"vetur.format.defaultFormatterOptions": {
        "prettier": {
            "singleQuote": true
        },
        "prettyhtml": {
            "singleQuote": true
        }
    }
```
