### ISSUE TITLE
Am I allowed to continue my existing project for P3?

### ISSUE THREAD

**Issue by ihimawan** [susanBuck/e28-fall19#108]
I think that my P2 project is good enough to be made as an SPA with "pages." I just want to make sure that before I continue, am I allowed to just continue off of my P2 project and work from there?

**Comment by susanBuck** [comment]
Yes, you can evolve P2 into P3 - but do it by making a copy of `p2` and renaming it `p3` - that way the original P2 project stays in tact.

**Comment by ihimawan** [comment]
Awesome, thank you!
