### ISSUE TITLE
I couldn't run "npm install -g @vue/cli"

### ISSUE THREAD

**Issue by mourad1974** [susanBuck/e28-fall19#109]
Hi,
I get this message when I'm trying to run the command  **"npm install -g @vue/cli"**, any idea why it's happening?

![Screen Shot 2019-11-03 at 8 04 09 AM](https://user-images.githubusercontent.com/35425870/68085615-bcae9280-fe10-11e9-9b91-625e938552c9.png)

Thank you

**Comment by andmade** [comment]
I received the same errors trying to install it on Ubuntu on Windows and running it as root wouldn't fix it. The solution for me was to reinstall node using nvm (which auto included npm) via these instructions: 

https://github.com/nvm-sh/nvm/blob/master/README.md

**Comment by coinshot** [comment]
@mourad1974 Have you tried ```
sudo npm install -g @vue/cli
``` ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mourad1974** [comment]
Thanks, @andmade @coinshot for the prompt, the "sudo" solved the issue
