### ISSUE TITLE
Clarification on quiz 9 question 1

### ISSUE THREAD

**Issue by phildarnowsky** [susanBuck/e28-fall19#110]
This question reads:

> This week you should set up your own ZipFoods practice application in your e28 repository,
> following the steps outlined in lecture.

What exactly are we trying to do here? Is it to replicate what you did down to the component names and filenames? Or are we trying instead to replicate the feature set of ZipFoods as you displayed it, and if so, which features are essential?

**Comment by susanBuck** [comment]
Yes, replicate, although getting component/file names exactly the same isn’t essential.

Idea is to follow along on your own end for practice, and to have that foundation in place to build upon in in coming weeks.
