### ISSUE TITLE
Copy Right for Images

### ISSUE THREAD

**Issue by audreychenjj-2019** [susanBuck/e28-fall19#112]
I wonder if we need to concern ourselves with the copy right for images for our p3 given it's going to be live to public. Is there any open source of images? I am planning to use only pictures I own but it would be quite time consuming to put together all the assets needed.

**Comment by pausman** [comment]
You can use [advanced image search](https://www.google.com/advanced_search)  or [creative commons](https://ccsearch.creativecommons.org/) to help find images that can be used without violating copyright.

**Comment by coinshot** [comment]
Use Unslapsh.com
All free, no need to give or mention credit, best source.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by susanBuck** [comment]
For project purposes, you just need to cite any outside images in your README.md file.

Ref:

![image](https://user-images.githubusercontent.com/237711/68164354-9a109c80-ff2a-11e9-92d5-6cb9fd546953.png)

The resources @pausman and @coinshot mentioned are great places to find free-to-use images.

**Comment by audreychenjj-2019** [comment]
Thanks for all the feedback!
