### ISSUE TITLE
Eslint import and file extensions (bug?) - Findings

### ISSUE THREAD

**Issue by conc2304** [susanBuck/e28-fall19#113]
Just wanted to share my findings to help avoid anyone else spending too long on this issue like I did.

Issue :
`import products from './products.js';` yields `Unexpected use of file extension "js"`
and
`import products from './products';` yields `Missing file extension for "./products`

what ended up mysteriously solving it was by importing `products.js` before any other imports
not sure why, but I hope that this saves someone some time and frustration

**Comment by susanBuck** [comment]
Thanks for sharing your findings, @conc2304! I wasn't able to recreate the issue on my end, but this is good info to have out there in case anyone else runs into this problem.
