### ISSUE TITLE
Filtering Method question

### ISSUE THREAD

**Issue by atanasgizdov** [susanBuck/e28-fall19#114]
Hi all,

Just curious if anyone can point me to some documentation on how the below method nesting from this week's example works in Vue. I understand the overall function and how it parses the object but having a bit of trouble visualizing how I would re-create this on my own for a different use case or further nesting

`featuredProducts: function() {
    function isMatch(product) {
        return product.categories.includes(this);
    }
    return this.products.filter(isMatch, this.category);
}`

**Comment by coinshot** [comment]
[Click here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) to see the MDN documentation.

Also,[ this video](https://www.youtube.com/watch?v=4_iT6EGkQfk) is fairly (in a simple way) explains the **filter** prototype.

---

And [THIS](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) is the docs for **Includes**

**Comment by susanBuck** [comment]
Closing this issue out, but feel free to re-open or start a new thread if you still have questions about filtering @atanasgizdov!
