### ISSUE TITLE
Can't create vue application

### ISSUE THREAD

**Issue by mihika-shilpi** [susanBuck/e28-fall19#116]
When I run `vue create zipfoods` it returns:

```
✨  Creating project in /Applications/XAMPP/xamppfiles/htdocs/e28/zipfoods.
⚙  Installing CLI plugins. This might take a while...

 ERROR  Error: spawn npm ENOENT
Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

Can't seem to find a solution on preliminary google searches...any ideas?

**Comment by coinshot** [comment]
Try ``npm install npm update``, then try again.

**Comment by mihika-shilpi** [comment]
:o that had me realise that somewhere between successfully installing Vue Cli and running the create command, npm as a package was no more available to me. I had to redownlaod npm and start over. Worked. Thank you!
