### ISSUE TITLE
Strange behavior w/ "npm run serve"?

### ISSUE THREAD

**Issue by gaderrick** [susanBuck/e28-fall19#120]
I'm working through video for axios (at about 4:24 for the time) and I'm getting the following error _only_ when I "re-save" the App.vue file.

``` ERROR  Failed to compile with 1 errors                                                                          9:18:52 AM

 error  in ./src/App.vue

Module Error (from ./node_modules/eslint-loader/index.js):
error: Unexpected console statement (no-console) at src/App.vue:34:17:
  32 |             )
  33 |             .then(response => {
> 34 |                 console.log(response.data);
     |                 ^
  35 |             });
  36 |     }
  37 | };
```

If I stop/restart "npm run serve" the error message goes away until I save the file again. Odd though, the API call is working. Looking on google it appears to have something to do with caching, but Susan's demo didn't have the issue. Any ideas?

**Comment by coinshot** [comment]
I remember @susanBuck mentioned this in the lecture, or in an issue. In any case, add this to your pakcage.json file:

``` 
...
    "rules": {
      "no-console": "off"
    },
... 
```

You may already have "rules" entry but it should be empty, so don't add it again, just add the "no-console" in it.

**Comment by gaderrick** [comment]
@coinshot - Thank you for that! As soon as I read your post it triggered my memory.
