### ISSUE TITLE
 Uncaught (in promise) Error in console tab

### ISSUE THREAD

**Issue by nnoel2626** [susanBuck/e28-fall19#122]
keep getting this error message at the console when a request is made to my GitHub API server.  On the network tab,  I have different massage:

`{user: "nnoel2626", repo: "e28", url: "https://raw.githubusercontent.com/nnoel2626/e28/master/db.json",…}
data: "404: Not Found↵"
repo: "e28"
status: 404
url: "https://raw.githubusercontent.com/nnoel2626/e28/master/db.json"
user: "nnoel2626"`

I can access the data when I enter the api-link below in the browser directly. But I can not get it to work when the request is made through the app.
https://my-json-server.typicode.com/nnoel2626/e28-zipfoods-api/
Can anybody help me with this issue?

**Comment by gaderrick** [comment]
It looks like the URL in your code is not pointing to the same url you're
putting I to the browser. Try changing the url to the e28-zipfoods-api one
in your code.

Jerry

**Comment by susanBuck** [comment]
Confirming @gaderrick's reply! Let us know if that doesn't do the trick @nnoel2626.

**Comment by nnoel2626** [comment]
Thank you all. I was able to fix the problem.
