### ISSUE TITLE
Project 2 sampling

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e28-fall19#128]
Hi everyone -

FYI I just released Project 2 grades/feedback in Canvas.

Below's a sampling of projects from your classmates to check out. I'm including the production URL as well as the Github URL if you want to explore the code underneath (which you're encouraged to do).

Tic Tac Toe
http://p2.hesibrodsk.me
https://github.com/ibrodsk76/e28/tree/master/p2

War card game
http://p2.andmade.me
https://github.com/andmade/e28/tree/master/p2

Find the hidden letter
http://p2.boopboop.io
https://github.com/cgloge/e28/tree/master/p2

Alpacan Mingle
http://p2.indrihimawan.com
https://github.com/ihimawan/e28/tree/master/p2

Rock, Paper, Scissors
http://p2-alt.rokmesojedec.live
https://github.com/rokmesojedec/e28/tree/master/p2-alt

Blackjack
http://p2.rokmesojedec.live
https://github.com/rokmesojedec/e28/tree/master/p2

Math quiz game
http://p2.nazm.us
https://github.com/naztronaut/e28/tree/master/p2

Shuffle tile game
https://p2.harvard.studio
https://github.com/coinshot/e28/tree/master/p2

Find the golden coin
http://p2.mihikashilpi.space
https://github.com/mihika-shilpi/e28/tree/master/p2

Practice music sight reading
http://p2.sprk.me
https://github.com/jeremysouthgate/e28/tree/master/p2

Multiplication table practice
http://p2-alt.mrtyson.me
https://github.com/mrtyson93/e28/tree/master/p2-alt

Skeeto
https://p2.dgmde28.cognize.org
https://github.com/extra808/e28/tree/master/p2

Game of life
http://p2.weswollner.me
https://github.com/weswollner/E28/tree/master/p2

Mystery word game
http://p2.teri-e28.me
https://github.com/terichadbourne/e28/tree/master/p2

**Comment by cgloge** [comment]
Woah. There are some really impressive games in there. 

I got lost in the Alpacan Mingle game for a while. :)

**Comment by apatruno618** [comment]
Great games everyone, everyone is so creative :)

**Comment by extra808** [comment]
Are you an [alpaca who enjoys long walks on the beach](https://www.reddit.com/r/aww/comments/dw4gyq/this_is_my_pet_alpaca_alfie_he_loves_the_beach/)?

**Comment by ra1101** [comment]
These are great !

**Comment by audreychenjj-2019** [comment]
Wow, those are very interesting game. I realize again how dull my game is.

**Comment by ibrodsk76** [comment]
Wow, so cool! Thank you for sharing!
