### ISSUE TITLE
Limitations with local storage

### ISSUE THREAD

**Issue by cgloge** [susanBuck/e28-fall19#129]
Hey classmates,

I plan on doing a recipe site for Project 3 since that project relates to my current work at a natural foods company. My team has been talking about revamping our recipe site for a while and had wanted to feature certain kinds of recipes (eg vegetarian, paleo, etc) based off a visitor's browsing history.

When we spoke to vendors, everyone said we needed the visitor to create a login to be able to do that, but now it seems like it should be possible using local storage. 

Does anyone know any reasons why this would be a bad idea? Are there any privacy regulation issues with it?. It's not collecting personally identifiable info so I think it should be fine, but would love to hear if anyone knows of any gotchas.

Best,
Carly

**Comment by coinshot** [comment]
We cannot create and store login info on the web storage, it's available on the end-user browser only, it's like cookies. You must have some sort of server that stores the info on some sort of database. Not mentioning that you must use some sort of encryption to store the credentials, you cannot just save them as text.

In my opinion, PHP is the best, but if you wanna stick to JavaScript and do it quickly, use "Express.js" to make your server. For the database, I suggest "MongoDB" since it's JSON like and you might find it easier, to begin with. 

So watch some Youtube videos on Express.js and MongoDB and you are good to go, both are super easy to learn.

**Comment by susanBuck** [comment]
👍to all of @coinshot's notes above.

You do need a server component to have a full login system.

I would recommend using some server-side framework to deal with the tasks of authentication (registration, login, restricting access, password resets, encryption, etc.)

For example, if you use PHP on the server, the framework Laravel comes with a complete auth system: https://laravel.com/docs/6.x/authentication.

[Here's a good article that explains how to integrate Vue and Laravel to have an auth system](https://codeburst.io/api-authentication-in-laravel-vue-spa-using-jwt-auth-d8251b3632e0).

I would not recommend building an authentication system from scratch. There's a lot that goes into it, and so it's best to rely on an existing framework that has been "battle tested".

All of that being said, for the purposes of this course and your P3/4, you could build a little "mock" auth system using just Vue.js and local storage.

__Rough outline:__

We'll rely on two local storage entries:

+ entry 1. **User details** `email` : `{ hashed password, name, recipes, etc. }`
+ entry 2. **Logged in status** `user` : `email`

When a user  "registers" it creates the first entry.
The password should be hashed - i.e. not stored as plain text.
For the purposes of this exercise, a [rudimentary hashing solution would work](https://gist.github.com/hyamamoto/fd435505d29ebfa3d9716fd2be8d42f0).

To "log in", the user fills out a form with their email and password.
You check local storage for a matching email (entry 1), and compare the hashed version of the password they entered, to the hashed version of the password stored.

If it's a match, create entry 2 (`user`: `email`).

When using the site, authentication is checked by looking for the presence of entry 2.

While logged in, entry 2 can be used to retrieve the user's email address, and this can be used to look up entry 1 if you need user details.

To log out, you delete entry 2.

**Of course this is not expected to be a real world auth system.** Using local storage for user details is neither secure nor permanent.

However, it would work for a simple prototype, and be an interesting exercise to a) practice a lot of the techniques we're learning and b) think about how a login system works.

**Comment by cgloge** [comment]
Sorry! I didn't really explain my question well.  I'm not looking to store login credentials but would like to customize a recipe site based off of browsing history _without_ requiring that user to create an account.

From a user experience, I think it's too high of friction to ask someone to create an account right off the bat to provide a customized recipe experience.

I assumed this is possible since websites save cart items without a login, but I haven't really seen sites customize page content outside of that.

**Comment by susanBuck** [comment]
>> customize a recipe site based off of browsing history without requiring that user to create an account.

I'd say that's doable with local storage. I'm imagining something where maybe each recipe has keywords/tags associated with it that are added to an array stored in local storage for the given visitor. Then, when the visitor goes back to the home page, you could retrieve those tags and do a query to the server for similar recipes that share those tags.

Something like that?

**Comment by iancallahan** [comment]
It's a cool idea and I can't think of any privacy issues for tracking in-site browsing behavior. 

It's really strange that the vendors told you that you had to force users to log in to have this feature. It could also be done easily on the server-side by storing data in the session, no login required. (E.g. [here's how it's done in Laravel](https://laravel.com/docs/5.8/session#storing-data).)

**Comment by ibrodsk76** [comment]
I was looking for something else related to local storage and stumbled upon this article:
https://www.rdegges.com/2018/please-stop-using-local-storage/

Just some food for thought before using local storage in a real production application.

**Comment by extra808** [comment]
Thanks @ibrodsk76. 

> [don't use local storage] Unless you need to store publicly available information that:

> Is not at all sensitive
> Doesn’t need to be used in an ultra high performance app
> Isn’t larger than 5MB
> Consists of purely string data

That leaves room for a ton of use-cases, especially if you decide that calling serialization an "ugly hack" is overly dramatic.

The most important points are about local storage's relative insecurity and, longer term, its unavailability to web workers.

**Comment by susanBuck** [comment]
I think that article title *"Please Stop Using Local Storage"* is misleading.... I think it should be called *"Please Stop Using Local Storage... For Secure Data and Other Things it Wasn't Designed For."*

As summarized by this paragraph:
>> To keep it short, here’s the only situation in which you should use local storage: when you need to store some publicly available information that is not at all sensitive, doesn’t need to be used in a high performance app, isn’t larger than 5MB, and consists of purely string data.

It's perfectly acceptable to use local storage in a real production application, it just depends on what you're using it for. 

No, you would not use it for a login system (as I hope my bolded disclaimer in my last post made clear :-), but things like saving a visitor's preferences/settings - that's a legit use for it.

**Comment by susanBuck** [comment]
Closing this thread as I think the original question has been addressed, but feel free to continue the discussion or start a new thread if any questions are still pending.
