### ISSUE TITLE
htdocs shortcut is not working

### ISSUE THREAD

**Issue by mourad1974** [susanBuck/e28-fall19#13]
Hi,
Does anyone has the same issue?
When I type the shortcut "htdocs" it doesn't take me to **### **"/Applications/XAMPP/xamppfiles/htdocs"****, instead it shows the message: 
 
![Screen Shot 2019-09-13 at 4 02 16 PM](https://user-images.githubusercontent.com/35425870/64891705-a837f000-d640-11e9-980c-5ebc02355113.png)

I dont have MAMP installed  on my Mac desktop , the same thing when i try it on my laptop.

**Comment by pausman** [comment]
there was a typo originally in the notes.  It has been fixed to 
alias htdocs='cd /Applications/XAMPP/xamppfiles/htdocs'

**Comment by mourad1974** [comment]
Thank you for replying,
I did check "**sudo nano ~/.bashrc"** everything is correct  with the right path to htdocs, but the terminal still give me the same message

**Comment by mourad1974** [comment]
Thank you, i did paste the corrected file but for some reasons an old path remained there
