### ISSUE TITLE
Quiz Week 11 Q2 Typo: `vue ci` should be `vue ui`

### ISSUE THREAD

**Issue by guezandy** [susanBuck/e28-fall19#131]
Question 2:

To try it out, run `vue ci` in the command line. 

Should be 
`vue ui`

**Comment by spttruong** [comment]
Beat me to it! Ran into the same issue just now. Thanks for posting!

**Comment by susanBuck** [comment]
Oops, yes, should be *vue ui*.

Thanks @guezandy!

I’ll update the question next time I’m at my computer.

**Comment by susanBuck** [comment]
Corrected this in the quiz, but going to leave this post up in case anyone is seeing the older version.
