### ISSUE TITLE
issue in production server  

### ISSUE THREAD

**Issue by mourad1974** [susanBuck/e28-fall19#132]
![Screen Shot 2019-11-16 at 8 25 10 PM](https://user-images.githubusercontent.com/35425870/69001656-9b3db400-08b0-11ea-8919-f210bf88a30c.png)

P3 working on my local server but when deploying it to the production server, it doesn't.  when I click on public, nothing happens and I get a blank page.  any idea?

**Comment by gaderrick** [comment]
What's the error? Did you change the server mapping (ie p3.loc to
p3.domainname.com)?

**Comment by mourad1974** [comment]
that's the message I get in the console

![Screen Shot 2019-11-16 at 9 07 31 PM](https://user-images.githubusercontent.com/35425870/69001923-4b152080-08b5-11ea-8bee-9c71c8754454.png)

**Comment by mourad1974** [comment]
yes I did set the virtual host in my server to p3.doimaine.com

**Comment by coinshot** [comment]
Where is your dist folder? Have you built it yet? If not, run`$ npm run build` and make sure your virtual host is set to load up from that dist folder.

**Comment by mourad1974** [comment]
thank you, where do I have to build the dist folder and which command

**Comment by mourad1974** [comment]
Thank you, Ali, I just built dist folder $ npm run build  and nothing seems to happen

**Comment by gaderrick** [comment]
What error are you getting now?

**Comment by mourad1974** [comment]
the error only in the console, but the page in blanc
![Screen Shot 2019-11-16 at 9 07 31 PM](https://user-images.githubusercontent.com/35425870/69002810-4310ad00-08c4-11ea-802e-6a3729434d0d.png)

**Comment by mourad1974** [comment]
the error is only in the console, but the page is blanc
![Screen Shot 2019-11-16 at 9 07 31 PM](https://user-images.githubusercontent.com/35425870/69002838-a7cc0780-08c4-11ea-975b-effde31e1fd7.png)

**Comment by gaderrick** [comment]
What's the content of your vue.config.js file?

**Comment by gaderrick** [comment]
I came across this that seems similar... [https://github.com/vuejs/vue-cli/issues/2357](url).

**Comment by mourad1974** [comment]
Thank you so much @gaderrick, Just solve, I did not include dist in my virtual host, so I had to point it to dist instead of the root of the directory e28/p3/dist and not e28/p3
