### ISSUE TITLE
Reusing form for adding and editing

### ISSUE THREAD

**Issue by gaderrick** [susanBuck/e28-fall19#133]
Does anyone have a good resource they can point me to for reusing a component to both add and edit an "object" (in my case a recipe)? I'm thinking I need to create an empty object and then populate it in the mounted section, but not sure.

**Comment by naztronaut** [comment]
If I understand your thinking, I think you're on a good path. But these are my thoughts on this:

Do you have either an 'add' or 'edit' component created already? If you do, then you can encase all of it in logic that does the other piece. 

For example, if you have Edit set up where the component receives your Recipe Object and populates the form fields, in your mounted section, you can do something like (here's some pseudo code: 

```
if(Recipe.Object exists) {
    this.recipe = Recipe.Object;
} else {
    this.recipe = newBlankRecipeObjectThatYouDefineSomewhere;
}
```
`this.recipe` refers to an object in your component that you define in the data and the Recipe.object is either something you get through props or something.  `this.recipe` is also what your HTML is consuming to populate the HTML. Then you can use similar logic in your 'save' method to either update (PUT) or create (POST) the recipe.

**Comment by gaderrick** [comment]
Thanks for the nudge in the right direction. It ended up being a lot more work than I thought but it seems to be working now :).
