### ISSUE TITLE
missing param for named route "product" error

### ISSUE THREAD

**Issue by nnoel2626** [susanBuck/e28-fall19#134]
I followed the instruction from Susan in week10 part2 video. I did exactly what she did. The only difference, I used a route.js file instead of putting it in the main.js file. But I keep getting the error message below from the console:
`` [vue-router] missing param for named route "product": Expected "id" to be defined.vue.runtime.esm.js?2b0e:619 [Vue warn]: Property or method "product" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components``

Does anyone know how to solve this issue?
I am pushing my code now to GitHub.

**Comment by coinshot** [comment]
The Ajax call hasn't yet finished fetching. 
Assuming you're using Axios, it returns a promise so you can handle it async and pause Vue to render if your stuff isn't loaded up. Do the Axios call on App.vue, so you make sure nothing is being rendered before all data is loaded up, and define a global mixin data option so you can access it everywhere:

1. Create global mixin data in your **main.js**:

```
Vue.mixin({
  data: () => ({
    globalData: [],  
    globalLoaded: false
  })
})
```
 
2. In your App.js, stop the page to render while **globalLoaded** is false:
```
<template>
    <div  v-if="globalLoaded">
        ...
    </div>
</template>
```
3. In your App.js, on mounted(), make the Axios call, set the globalLoaded to true, and add the  **globalData**:
```
axios.get(reviewsUrl)
    .then(res => {
        ...
        this.globalData = res.data
        this.globalLoaded = true        
    })
```

Now you can use **globalData** in any component you like and do your stuff with it, change it and whatever you like.

**Comment by gaderrick** [comment]
Hmmm... I ran into something similar. Assuming your route looks like this:
```javascript
{ path: '/product/:id', component: ProductPage, name: 'product', props: true },
```
Make sure that you have the following defined on the products page:

```javascript
export default {
    name: "ProductPage",
    props: ["id"],
    components: {},
...
```
That's probably what's causing the missing param symptom.

**Comment by gaderrick** [comment]
What is your github link? Sorry, just missed you were posting it.

**Comment by nnoel2626** [comment]
Yes, this the same way I set up both my routes and my ProductPAge component.

**Comment by coinshot** [comment]
Where did you make your Axios call?

**Comment by nnoel2626** [comment]
I am still using a local product.js file. I have not implemented axios yet in my project.

my githup: https://github.com/nnoel2626/e28

**Comment by gaderrick** [comment]
Take a look at your router.sj file. It has:
```javascript
        {
            path: '/product/:id',
            name: 'product',
            component: ProductDetailsPage,
            // custom logic for mapping between route and props
            props: (route) => ({
                ...route.params
            })
            //props: dynamicPropsFn
        },
```

But your file is expecting:
```javascript
export default {
	name: "ShowProduct",
	props: ["product"]
};
```
The two have variables have to match.

**Comment by coinshot** [comment]
First, in your **Navbar.vue**, you have "product" in your for loop, but "product" needs a param, so either **remove** "product" from the **links** array or have a condition like below in your router-link so it does not throw an error

```
<li class="navItem active" v-for="link in links" :key="link">
	<router-link v-if="link != 'product'" exact :to="{ name: link }">{{ link }}</router-link>
</li>
```

Then, you have not defined "product" in your **ProductDetailsPage.vue**, but you a `v-if="product"` in the template. If you fix the one above you get rid of the error for the param, then here you need to get the id, load the products and filter it by the id to get your single product.

**Comment by nnoel2626** [comment]
Great catch! Looking at the code for so long, I just can not see my own mistake. Thank you so much.
