### ISSUE TITLE
Question: How to format list data from a data source for display, the Vue way?

### ISSUE THREAD

**Issue by bibliodrone** [susanBuck/e28-fall19#137]
This is actually a simple question: 

I have a data key called "posts.categories", which takes a list of values, which represent the tags for a blog post, for instance:
```
posts [
   { id:1, 
     categories: ['general', 'opinion', 'food'],
     ...
    }, 
    ...
]
```

Simply using this data in a template slot like this, passed from a child component (which is why it is 'post' here and not 'posts') :

`<div class='post-category'> {{ post.categories }}</div>
`
gives me a display on the web page as though I were printing the array, 

`['general', 'opinion', 'food']`

which is not ideal; I would of course prefer to display the strings from each index individually such as  **"general, opinion, food"**, perhaps using an un-ordered list. I thought perhaps there was a way to use 'v-for' to do this, but I haven't been able to get it to work that way.

I am sure this has come up somewhere, and I have gone through some attempts using the Vue documentation but there doesn't seem to be a clear answer on the Vue syntax for accomplishing something this simple.  I know how I'd do it using JavaScript, but I though there must be an integrated 'Vue' way to do it. 

Thanks, 

-Gerry

**Comment by extra808** [comment]
Yes, this is what [v-for](https://vuejs.org/v2/guide/list.html) is for, using each item in an array: `v-for='category in post.categories'`. If it didn't work for you, maybe there was a typo?

Make sure to bind a `:key`.

**Comment by susanBuck** [comment]
👍to @extra808's comment. 
Feel free to share a code snippet/your repo if it's not working on your end, @bibliodrone.

**Comment by bibliodrone** [comment]
Thanks for the support, the problem was with how I was using the key value; once that was resolved, this worked just fine:

```
<li v-for='cat in post.categories' :key='cat'>
                {{ cat }}
</li>
```
