### ISSUE TITLE
what to do when you reached the maxContentLength allowed by the API?

### ISSUE THREAD

**Issue by apatruno618** [susanBuck/e28-fall19#138]
My P3 utilizes recipes and unfortunately, it seems like my .json file reached the max size allotted by My JSON Server. I don't really want to start cutting back on the content because it would really take away from the application, is there another reliable and simple API option we can use?
![Screen Shot 2019-11-19 at 10 50 51 PM](https://user-images.githubusercontent.com/35854109/69207973-e3164280-0b1f-11ea-9fd9-f64b5352b182.png)

**Comment by naztronaut** [comment]
Some asked if they could do an AJAX request to a json file in the public/ directory here in this issue: #124 

@susanBuck said it was okay so maybe that will help. But you won't be able to call individual IDs like you can with my-json-server (e.g. /database/object/{id}) and I don't know if there are any good alternatives without you making your own backend service (at least I haven't found one). 

I ran into a the same limitation but ended up trimming my content.

**Comment by susanBuck** [comment]
👍 to @naztronaut's notes.

If you want a more robust solution, you could try something like https://buttercms.com. It's a headless content management system, so it's basically an API for blog stuff - posts and pages, etc. However, it also supports collections, which you could use as your data source.

[They offer a free developer plan for personal non-commercial usage.](https://buttercms.com/pricing/)

As an example, I set up a collection for `products` and loaded it with 2 sample products; here's what a call to the API looks like:
https://api.buttercms.com/v2/content/products/?auth_token=1e91747b69929f0735a0489857b1cf06cf04dc45

Here's what the backend looks like for managing the products:
![image](https://user-images.githubusercontent.com/237711/69256161-0fb17500-0b87-11ea-97f1-f42cdcf07321.png)

[Here are the docs for their API...](https://buttercms.com/docs/api/?shell#introduction)

[They also have a API-client specific to Vue JS which you can read about here...](https://buttercms.com/docs/api-client/vuejs)

**Comment by gaderrick** [comment]
@susanBuck do we need to implement the larger storage for P3? I ran into the same issue do to the size/content of my recipe objects.

**Comment by susanBuck** [comment]
@gaderrick You're welcome to, but not required to. The most straightforward solution is to trim you sample data until you're below the limits. That'll be sufficient for P3.

Because a few students have reported running into the limits, I'll go over some API alternatives you can use in P4. I'll cover this in either Week 12 or 13.

**Comment by gpunzalan18** [comment]
I am doing a blog application and ran into the same issue. The requirements said that
>Some data must be retrieved from your mock server

So to satisfy that, I retrieve **some** of my blog data using a mock server. This includes an ID, blog title, and a short snippet of the post. And within my application, I have a json file that contains the rest of the post with their corresponding ID. I just have some logic in my code that maps the the data from my mock server with my json data using the IDs

@susanBuck is this approach okay? If so, @apatruno618 maybe this could be an option for you!

**Comment by susanBuck** [comment]
@gpunzalan18 That's a creative workaround. Absolutely fits P3 requirements. 👍

I could see a similar implementation in our ZipFoods example - the majority of product data is static, but things like inventory count are dynamic and fetched from the server.

**Comment by andmade** [comment]
I followed this article to create my own mock api server locally so I didn't have to wait for the website to update all the time or deal with their cached responses:

https://medium.com/backticks-tildes/building-a-mock-rest-api-with-json-server-812ed3e6036a

It's been working great for me and is very similar to the website in terms of setup. Supposedly it also has the ability to write changes as well, but I haven't played with that function.

**Comment by kreinholz** [comment]
Upon looking into Firebase further, I believe it is a viable workaround to my-json-server size limitations and also requires the least amount of additional setup as compared to more robust options. I was going to resurrect an old Express server app and use MongoDB to get a real database to work with, but the work involved with setting up/modifying an Express server app, making database calls, handling promises, catching errors, etc...it's way too much extra work that can and should be spent focusing on the Vue app for p4.

I think Firebase, with its ability to use JSON, but without the size constraints of my-json-server, should be fully adequate for p4's API access to data, and keep the focus where it belongs: on the Vue app. Thanks all for the helpful suggestions!

**Comment by kreinholz** [comment]
Confirmed that for "Read" operations, at least, Firebase is a huge improvement over my-json-server and does everything I need it to for p4. Fantastic!
