### ISSUE TITLE
project4 - option to use an Express server to provide API routes to our Vue app?

### ISSUE THREAD

**Issue by kreinholz** [susanBuck/e28-fall19#139]
I know project3 isn't quite due yet, but several of us have noted frustrations with the limitations of a mock API. I also realize from the discussion around Issue #138 that we'll be given additional API options over the course of the next few weeks.

That having been said, would it be permissible to use our own Node.js/Express server to provide our API routes for project4? I recognize that the focus is on front-end development and that spending a bunch of time setting up the Express server is valuable development time taken away from the front-end elements of project4 that are actually our learning objectives (and presumably, what we'll be graded on). However, I have a github repository with the source code to an Express server with API routes already set up for the 4 CRUD operations, connected to a MongoDB cloud database, courtesy of CSCI E-31. I believe that with a few modifications, I could adapt that server for use with project4, assuming my project4 is an expansion of my project3. I'd just have to create a second Digital Ocean droplet to run the Express server from. This would not be a "convert an Angular front-end to a Vue front-end" exercise. The CSCI E-31 app was for photo sharing, not blogging (although on the server end, there's certainly a fair amount of overlap, which is why I think I could adapt it for use with project4 without it taking too much time).

The reason why this interests me is that I did a blog for project3, and I was really dissatisfied with the small amount of data I was able to mock using my-json-server. I felt like it didn't allow me to fully showcase what my app did, and moreover, since I couldn't persist data except by recourse to localStorage, what I really want to do, for project4 that is, is have users authenticate (optional) and create new blog posts (requirement in my mind) that will then be added to the database and retrieved and displayed by my Vue application. I'm guessing we won't have to support all 4 CRUD operations for project4 since we're not focusing on the server-side, although if I fired up my Express server I could have my Vue app interact with the API routes to perform all 4 CRUD operations. But mainly, Create and Read are what I'm interested in. With mock data I'm stuck at Read, and that feels really limiting.

I know I'm probably getting ahead of myself, but before I start prepping my old Express server and creating a home for it on Digital Ocean for my Vue app in project4 to interact with, I wanted to make sure this was a feasible/desirable thing to do. If I'm missing the point of project4, and would be better served changing directions, I'm definitely open to that. That's mainly why I'm asking the question now, before I'm super committed to a particular code base or course of action.

**Comment by susanBuck** [comment]
Hi @kreinholz - Yes, you're welcome to create your own API server for Project 4 if you've got the time/experience to devote to that task. 👍

**Comment by kreinholz** [comment]
@susanBuck thank you! I'll probably do just that, provided I can get the Express server modified and running on a new Digital Ocean droplet within the next week or so, to allow me to focus on the Vue aspects of project4 and the client-side!

**Comment by extra808** [comment]
You can run the Express service on the same droplet as your class Apache service if you set the port number Express is configured to listen to something other than port 80 (and 443 if you're using HTTPS).

This [Express Hello world](https://expressjs.com/en/starter/hello-world.html) example shows running it on port 3000, it looks like the number is an argument to app.listen().

**Comment by kreinholz** [comment]
Thanks, @extra808! That’ll save me $5-6 to not have to set up a second Digital Ocean droplet! 😁

I would offer to provide a public Github link to my Express server for anyone wishing to do likewise, but I don’t want to spoil CSCI E-31 for those who haven’t, but might, take it, plus you would have to reconfigure Mongoose and set up your own MongoDB cloud server in order for it to work, so I think that would muddy the waters/unduly expand the scope of project4 for anyone who doesn’t already have an Express server configured like this. As an aside, I highly recommend CSCI E-31, which aside from this class has been my favorite class taken at HES. There are a lot of similarities in terms of teaching style and participation, so if you like Professor Buck, Professor Bouthilier is another HES gem.

My plan is to spend the week we have no class trying to modify and deploy my Express server for use with project4, and use it for my axios API calls. I don’t want the Express server to turn into a distraction from the Vue client-side aspects of project4.

I’m also thrilled we covered unit and e2e testing this week. Other HES courses have mentioned the importance of testing, but this is the first course I’ve taken (and it’s my 5th in the CS world) to actually teach the “how to.” 👍

**Comment by kreinholz** [comment]
For anyone else thinking of doing something like this with their Digital Ocean droplet, running an Express/Node.js server with API routes in addition to their Apache server hosting all of our e28 projects, here are some useful links:

[https://www.digitalocean.com/community/questions/nodejs-and-apache-in-the-same-doplet](https://www.digitalocean.com/community/questions/nodejs-and-apache-in-the-same-doplet)

And perhaps right to the nitty-gritty:

[http://www.codingtricks.biz/run-nodejs-application-apache/](http://www.codingtricks.biz/run-nodejs-application-apache/)

**Comment by coinshot** [comment]
Have you had the chance to look into the Realtime Database in Firebase @susanBuck showed in the lecture? You can do pretty extensive filtering just by query params, it's powerful stuff, it might save you some headache dealing with Express and all: [Retrieving Data](https://firebase.google.com/docs/database/rest/retrieve-data)

Just a thought

**Comment by kreinholz** [comment]
@coinshot, totally get it, Firebase is my backup plan if I can't spin up the Express server real quick. In my use case, however, I believe I can modify an existing Express server code base I already have written, linked to MongoDB Atlas cloud db hosting. The end result is a permanent home for my data that will outlast this class, which for personal reasons, interests me. (I have a website currently hosted on WordPress that I'd like to "liberate" and host on my own custom server that can also run web apps like p2 and future projects). So it's an unnecessary extra step for p4, but for my own use, potentially a good long-term move. What I like about MongoDB is that it's BSON, basically JSON, unlike all of the SQL variants out there. The Express server is simply a means of providing API access from my Vue app to my MongoDB hosted data. To the Vue app, it'll be very much like retrieving data from Firebase or even my-json-server, except all 4 CRUD operations are supported, the data is more secure, and I can use it beyond this course.

**Comment by coinshot** [comment]
No, I get that.

> except all 4 CRUD operations are supported, the data is more secure

You can create, read, update and delete on Realtime Firebase, and have it pretty dang secure. Just sayin' :v:

**Comment by kreinholz** [comment]
@coinshot you are totally right. After more poking around, I believe Firebase will get the job done, with considerably less work involved than modifying an Express server app and MongoDB setup just to provide API access to data without the size limitations of my-json-server. Thanks for planting the seeds...you just saved me a ton of work!
