### ISSUE TITLE
JavaScript Game - Can use base our code on the provided example?

### ISSUE THREAD

**Issue by claudiomanuelboston** [susanBuck/e28-fall19#14]
Hello, not an issue but a question, Can we take the professor's code (Head and Tails) as the base and make changes to that one to make it work for the game we are supposed to write?
Thanks
Claudio

**Comment by ihimawan** [comment]
I assume so. I used her code structure as reference as to how to structure my files (I'm not too experienced in vanilla javascript projects). At least I don't think that counts as plagiarism :)

**Comment by susanBuck** [comment]
That's ok - just make sure you're understanding all the code you're working with/restructuring. 👍

In actual projects (coming later in the semester) I'll be more particular about doing a copy/paste/rewrite of project examples I provide, but I'll make note of it so you're aware.
