### ISSUE TITLE
App deployment in folder structure

### ISSUE THREAD

**Issue by vanillacandy** [susanBuck/e28-fall19#140]
I deployed my app on server, but it's in folder structure instead of rendering the app. Can somebody remind me which step I might have missed?

**Comment by susanBuck** [comment]
It looks like you're missing the steps of running `npm run build` to create a `/dist` folder, and pointing your VirtualHost to that `/dist` folder.

Here are the notes you're looking for: 
https://hesweb.dev/e28/notes#/vue/build-comprehensive?jump=deploy-to-digitalocean

**Comment by vanillacandy** [comment]
That works! Thank you for the reminder.
