### ISSUE TITLE
Solutions for "error: Unexpected console statement (no-console)"

### ISSUE THREAD

**Issue by audreychenjj-2019** [susanBuck/e28-fall19#141]
While the browser's developer tools and the Vue plugin are valuable, there are some obscure situations, had one such today, the console.log statements end up being very useful. However, you'll get the error 
`error: Unexpected console statement (no-console)`

Among the solutions are

- Globally turn off the check: Go to eslintConfig "rules" in package.json change the setting to "no-console": "off"

- Locally turn off the check: Use a comment before and after the offending console.log line like this
```
/* eslint-disable no-console */
console.log(someThing);
/* eslint-enable no-console */
```
- My favorite - Just add window before it, like
`window.console.log(someThing);`
This has been immensely helpful to me for debugging without having to go modify package.json or figure out what that eslint comment was supposed to be. Hope this helps you too.

**Comment by susanBuck** [comment]
Great summary; thank you for sharing @audreychenjj-2019!
