### ISSUE TITLE
Anything else to submit other than assignment week 11?

### ISSUE THREAD

**Issue by audreychenjj-2019** [susanBuck/e28-fall19#142]
Do we need to submit something special for p3 after putting it to production server? For example, submission of the production link etc in p1.

**Comment by susanBuck** [comment]
You need to submit P3 in Canvas - Details/link here: 
https://hesweb.dev/e28/projects/3#Submissions

**Comment by audreychenjj-2019** [comment]
I'm glad I asked. Thank you Susan!
