### ISSUE TITLE
Issues with loading P3 on Digital Ocean Production Server

### ISSUE THREAD

**Issue by spttruong** [susanBuck/e28-fall19#143]
I've followed all the steps on the [comprehensive build guide](https://hesweb.dev/e28/notes#/vue/build-comprehensive) but my p3 won't load. I can successfully ping my server. I've been trying to find the problem for a few hours now and I don't know what to do anymore. Any help would be much appreciated!

Project is working fine locally.
![project on local server](https://user-images.githubusercontent.com/49035567/69401750-e3e7d980-0cc3-11ea-9696-d2b6890f30bd.jpg)

After SSHing into my droplet, pulling from Github, running`npm install`, and finally `npm run build` this is what I got.
![npm run build success](https://user-images.githubusercontent.com/49035567/69401917-5c4e9a80-0cc4-11ea-8c64-c6db49f4cc4f.jpg)

./p3/dist directory is present:
![dist files](https://user-images.githubusercontent.com/49035567/69401957-77b9a580-0cc4-11ea-9c24-9296a03cea54.jpg)
 
Updated Virtual Hosts config
![vhosts](https://user-images.githubusercontent.com/49035567/69401991-91f38380-0cc4-11ea-9c64-d4f1b038fb45.jpg)

executed `service apache2 restart` and still saw this
![unable to load project](https://user-images.githubusercontent.com/49035567/69402915-3a0a4c00-0cc7-11ea-9696-4525e5f04408.jpg)

My previous projects load fine.

**Comment by spttruong** [comment]
Also, @susanBuck  will I lose points because my project is technically not successfully deployed to production and it's now past the non-late deadline? My last meaningful commit for this project was before 11:59pm. Thank you!

**Comment by naztronaut** [comment]
Try clearing your cache or try incognito. It works for me: 

![image](https://user-images.githubusercontent.com/8021112/69402932-455d7780-0cc7-11ea-988d-f49c8253e603.png)

**Comment by spttruong** [comment]
@naztronaut Thanks! That totally slipped my mind.
