### ISSUE TITLE
p3 peer review

### ISSUE THREAD

**Issue by pausman** [susanBuck/e28-fall19#145]
So is it safe to assume if a p3 project exists in a repository that we are to review that it has been submitted?

Thanks

**Comment by susanBuck** [comment]
Yup!

**Comment by madushag** [comment]
@susanBuck  - What if the project assigned to me does not have a completed README file, including a working production URL?

**Comment by pausman** [comment]
Mine was not 'ready' either.  I figured it might just be a late submission so am waiting until next week to see if it gets submitted.

**Comment by susanBuck** [comment]
@madushag it likely means that student hasn’t submitted yet. Give it until the cutoff on the 28th; if there’s nothing after that send me an email.
