### ISSUE TITLE
Question on video (part 2) - Categories page

### ISSUE THREAD

**Issue by gaderrick** [susanBuck/e28-fall19#146]
@susanBuck, during the part 2 video you mentioned you would be posting the code for the categories page to github. I tried every trick in the book (computed properties, watches, etc) to get it working, but fell short. The issue I'm having is that I can get the products array to load, but the loadCategories function doesn't update on the page until I hit ctrl-R or F5.

Do you know when you'll have it posted, or did anyone else figure it out?

**Comment by susanBuck** [comment]
@gaderrick Thanks for the reminder! I'm on mobile now, but I'll pushed the changes once I'm back at my computer.

**Comment by gaderrick** [comment]
Thanks!

**Comment by susanBuck** [comment]
Here you go: 

https://github.com/susanBuck/e28/blob/master/zipfoods/src/components/pages/CategoriesPage.vue#L28

I used a computed property, with a dependency on `products`. That way, once `products` is ready, `categories` will be updated.

**Comment by gaderrick** [comment]
Works perfectly. I was wrapped up in trying to make the mounted section work. Thanks!
