### ISSUE TITLE
DigitalOcean - Apache server config for SPA routing

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e28-fall19#147]
Hi everyone,

I was just testing out something on Zipfoods on production and realized I forgot a step of configuring Apache to work with SPA routing. : )

To see what I mean, go to your P3s on production... you'll note that you can navigate from page to page without issue, but, if you refresh while one of the routes you'll get a 404 error page.

It works when you navigate from page to page because it's just the Vue Router JS updating the URL and loading the page via the client.

But, if you refresh the page on a route, for example `/products`, it makes a request to the server, where it finds no such `/products` directory.

To fix this, we just need to configure Apache so that all traffic - regardless of the URL path - runs through the main `index.html` file.

I've updated the notes to explain how to do this:

> https://hesweb.dev/e28/notes#/vue/build-comprehensive?jump=preparing-to-deploy-to-digitalocean

You can also read more about this in the Vue Router docs section on HTML5 History Mode where it provides several example server configurations:

https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations

**Comment by susanBuck** [comment]
Follow-up to note that it's not required you have this in place for P3; obviously it's on me for forgetting to mention it earlier!

**Comment by extra808** [comment]
Thanks. I discovered this issue finishing P3 and made the changes in Apache. It’s good to know not to check this in peer reviews.

**Comment by nhillsbos** [comment]
Hello,

I just added the file and rebuilt the website. I am still getting a 404 error. What else might be causing the issue?

Also,  I noticed that the .htaccess file seems to be invisible. Is this normal?

**Comment by naztronaut** [comment]
@nhillsbos - It's normally not needed for a simple .htaccess modification but maybe try restarting apache:

```
sudo service apache2 restart
```

If that doesn't work, clear your cache or try an incognito window. 

It's normal for dot files to not be visible. To see those files try `ls -a` or `ls -la` and it'll list everything. It's the only way to see your .gitignore files as well.

**Comment by rokmesojedec** [comment]
Hi @nhillsbos 

I'm writing the peer review for your project and I managed to fix a 404 error caused by the way one of your router paths is programmed. 

I was able to reproduce the 404 Axios GET Request Error when navigating to favorite posts page by using browser's back and forward buttons or refreshing that page. You get the following error in the console:
```
Failed to load resource: the server responded with a status of 404 ()
createError.js:16 Uncaught (in promise) Error: Request failed with status code 404
    at t.exports (createError.js:16)
    at t.exports (settle.js:17)
    at XMLHttpRequest.p.onreadystatechange (xhr.js:59)
favs:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```

This can be fixed by changing the favorite posts router path from `post/favs` to `/favs`. I've described in greater detail why this is happening in the peer review. I will submit it shortly.

**Comment by nhillsbos** [comment]
Wow, thank you very much. I look forward to your peer review and I'll make the change you suggested.

**Comment by audreychenjj-2019** [comment]
My Apache server config on DigitalOcean does not work as expected for direct URL to pages on routes.

They work fine on my xampp server. Also all routes work when clicked within my application. Only on Apache if I include the route in the URL, I get the "Not Found" error. In other words .htaccess is not having the desired effect. 

I tried for my p3 based on [our notes](https://hesweb.dev/e28/notes#/vue/vue-router?jump=routing-modes-hash-vs-history). I still can't get it working with Susan's post above. I cloned Susan's zipfoods into my zipfoods3.acjj.me and still not working. That leads me to guess that I may be missing some other Apache config.

Any tips on how best to troubleshoot?

**Comment by coinshot** [comment]
@audreychenjj-2019  Have you placed your htaccess file in the public folder?

**Comment by susanBuck** [comment]
Hi @audreychenjj-2019 

I don't see a `.htaccess` file in your [`/p3/public`](https://github.com/audreychenjj-2019/e28/tree/master/p3/public) directory.

Can you double check on that?

**Comment by audreychenjj-2019** [comment]
Currently, I'm experimenting with a copy I made of your zipfoods in my zipfoods3. That way I eliminate other factors causing the error. I had created .htaccess in DigitalOcean prior to p3 submission, but as it was not working I took it out to avoid unintended results. 

I see .htaccess in my /zipfoods3/public directory. I also see .htaccess in my /zipfoods3/dist directory on DigitalOcean. Both contain 

```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /
    RewriteRule ^index\.html$ - [L]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . /index.html [L]
</IfModule>
```
The [app works](http://zipfoods3.acjj.me/). However, adding routes to the URL for [products](http://zipfoods3.acjj.me/products) or [categories](http://zipfoods3.acjj.me/categories) still results in the "Not Found" error.

In /etc/apache2/sites-enabled/000-default.conf I see -
```
<VirtualHost *:80>
  ServerName zipfoods3.acjj.me
  DocumentRoot "/var/www/html/e28/zipfoods3/dist"
  <Directory "/var/www/html/e28/zipfoods3/dist">
    AllowOverride All
  </Directory>
</VirtualHost>
```

I'm missing some detail here.

**Comment by naztronaut** [comment]
I wonder if mod_rewrite is disabled on your machine. Run this and see what it says:

```
sudo a2enmod rewrite
```

If it's enabled, it'll tell you. if not, then it'll enable it then restart Apache. 

I have my  .htaccess in the root directory (`/var/www/html`) and all of my e28 stuff is in `/var/www/html/e28` and the effects cascade down.

**Comment by audreychenjj-2019** [comment]
> I wonder if mod_rewrite is disabled on your machine. Run this and see what it says:
> 
> ```
> sudo a2enmod rewrite
> ```
> 
> If it's enabled, it'll tell you. if not, then it'll enable it then restart Apache.
> 
> I have my .htaccess in the root directory (`/var/www/html`) and all of my e28 stuff is in `/var/www/html/e28` and the effects cascade down.

Thank you! Works now after a2enmod rewrite and restarting Apache service. 

Was trying to understand why this worked and found this [article](https://www.digitalocean.com/community/tutorials/how-to-rewrite-urls-with-mod_rewrite-for-apache-on-ubuntu-16-04) with the following snippet perhaps useful for others too -

> First, we need to activate mod_rewrite. It’s available but not enabled with a clean Apache 2 installation.

**Comment by susanBuck** [comment]
Apologies for not including enabling mod_rewrite in the instructions! I realize now I had already enabled it on my DO server earlier in the semester, which is why it was working for me w/o that step.

Sorry for the confusion, and thanks @naztronaut for the catch!

**Comment by terichadbourne** [comment]
I was able to get his working with Netlify for P4 but not with Apache on Digital Ocean for P3. 

Here's what I've tried... tried the page reload on the [live site](http://p3.teri-e28.me/) after each of these steps with no luck: 
- Added `public/.htaccess` file with provided code and pushed to GitHub (see https://github.com/terichadbourne/e28/blob/master/p3/public/.htaccess)
- SSHed into Digital Ocean and ran `git pull` from  `/var/www/html/e28`
- Ran both `service apache2 restart` and `sudo a2enmod rewrite` from that directory
- It told me ```Enabling module rewrite.
To activate the new configuration, you need to run:
  systemctl restart apache2
```
- So I did `systemctl restart apache2` still in `e28` directory
- Moved to `p3` directory and tried `sudo service apache2 restart` again
- Confirmed the `.htaccess` file indeed made it to Digital Ocean
```
root@e28:/var/www/html/e28/p3/public# ls -a
.  ..  .htaccess  favicon.ico  index.html
```

Any ideas?

**Comment by naztronaut** [comment]
@terichadbourne - Try putting the .htaccess in your `/var/www/html` directory - the permissions should cascade down. I mine in my root and the contents are:

```
<IfModule mod_rewrite.c>
  RewriteEngine On
      RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} -f [OR]
      RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} -d
      RewriteRule ^ - [L]
  RewriteRule ^ /index.html
</IfModule>
```

It's a tiny bit different from what's done in the classnotes but the rewrite rules are pretty much the same. 

Enabling mod_rewrite and restarting apache are global actions so you can do those from any directory.

**Comment by susanBuck** [comment]
@terichadbourne The only step I didn't see you list was `npm run build`.

This step will copy the `/p3/public/.htaccess` file to `/p3/dist/public/.htaccess`, which is the location from which the browser will actually access the `.htaccess` file.

Can you try that/confirm you've tried that and let us know if changes anything?

**Comment by terichadbourne** [comment]
@susanBuck That was the trick! I just went to the `p3` directory again, ran `npm run build` and then `service apache2 restart` and things are now good on the live site. Thank you!
