### ISSUE TITLE
Cypress window not opening on Windows

### ISSUE THREAD

**Issue by gaderrick** [susanBuck/e28-fall19#148]
In the part 4 video, I'm following the instructions and added the cypress E2E package, but when I run the command "npm run test:e2e" the "cypress window" in the video isn't opening. I've tried clearly the cache and rerunning the command, but no luck. Any ideas?

**Comment by gaderrick** [comment]
Ugh... turns out on windows you apparently have to run: 

npm run test:e2e --headless option

Not sure why, but it works.

**Comment by gaderrick** [comment]
Here's a little more detail. When I run the npm run test:e2e the window that open shows the following:
![image](https://user-images.githubusercontent.com/10541760/69487491-7d2c0280-0e20-11ea-9386-ceb003e801dc.png)

**Comment by gaderrick** [comment]
Another update: I just fired it up on my MacBook and everything works as expected. Gotta love Windows.

**Comment by mrtyson93** [comment]
I experienced the same issue but was able to get a work around. When the test:e2e command finished running, run the command "node_modules\.bin\cypress.cmd open" from inside the zipfoods directory

**Comment by mrtyson93** [comment]
I spoke too soon, this error still came up when I was able to load cypress: 

![image](https://user-images.githubusercontent.com/10565392/69488703-1d8f2080-0e3b-11ea-9015-4bc44ef88575.png)

In solidarity my fellow windows users. Back to the drawing board.

**Comment by gaderrick** [comment]
I've gotten a little further, but the solution escapes me... this appears to be related to google not wanting to allow "localhost" to be navigated to. Grrrrrrrr.... unfortunately, Cypress appears to be defaulting to localhost:<port> for the server and for some reason the cypress.json file override settings aren't getting "picked" up.

Here's the link that started me down the rabbit hole:
https://stackoverflow.com/questions/33524826/localhost-not-working-in-chrome-127-0-0-1-does-work

**Comment by gaderrick** [comment]
This appears to be a significant bug that pops up in quite a few Chrome versions. I was able to get the GUI to stay open, but it still won't resolve to the zipfoods app even through the debugger shows:

```javascript
cypress:server:events sending ipc data { type: 'get:project:status', data: { id: 0.9553549787623175, data: { path: 'D:\\Development\\xampp\\htdocs\\e28\\zipfoods', state: 'VALID' } } } +1ms
```

**Comment by susanBuck** [comment]
Confirming I'm able to replicate this on my Window system. Same issue when running Cypress in headless mode w/ Electron (`node_modules\.bin\cypress run`). I'll do some troubleshooting and report back (if not today, on Monday!).

**Comment by kreinholz** [comment]
Thanks for pointing this out, @gaderrick. I hadn't gotten that far with my zipfoods app yet, but as a Windows user appreciate the heads up (and saving me the head scratching!). Look forward to a workaround/solution.

**Comment by susanBuck** [comment]
Found a workaround/solution.

First, start your webpack dev server like you usually would: `npm run serve`. We'll use this to test instead of the dev server Cypress boots up. 

Next, edit your Cypress config file in the root of your project directory (`/cypress.json`) and add a `baseUrl` config set to the address your webpack dev server runs on, e.g. `http://localhost:8081`:

```js
    return Object.assign({}, config, {
        fixturesFolder: 'tests/e2e/fixtures',
        integrationFolder: 'tests/e2e/specs',
        screenshotsFolder: 'tests/e2e/screenshots',
        videosFolder: 'tests/e2e/videos',
        supportFile: 'tests/e2e/support/index.js',
        baseUrl: 'http://localhost:8081'
    })
```

Then, in another tab, run `node_modules.bin\cypress.cmd open` to get Cypress to open (per @mrtyson93's note above). (Run it in another tab so that the dev server can continue to run in the other tab)

It should open so you can run your tests, and it should load the site via `http://localhost:8081`. 

![image](https://user-images.githubusercontent.com/237711/69501917-98a61480-0ed7-11ea-86d9-958230435518.png)

@gaderrick, @mrtyson93, @kreinholz  - Let me know if the above works on your end.

**Comment by gaderrick** [comment]
It works with a couple of tweaks/notes:
1) The file that needs the baseUrl setting is in `zipfoods\tests\e2e\plugins\index.js`
2) I didn't have to change the port on the baseUrl line from `8080` to `8081` though. My code block looks like index.js:
```javascript
return Object.assign({}, config, {
    fixturesFolder: 'tests/e2e/fixtures',
    integrationFolder: 'tests/e2e/specs',
    screenshotsFolder: 'tests/e2e/screenshots',
    videosFolder: 'tests/e2e/videos',
    supportFile: 'tests/e2e/support/index.js',
    baseUrl: 'http://localhost:8080'
  })
```
3. I did still have to start the server normally in a separate tab or cmder.

All the tests are running now. Thanks, @susanBuck ! I was trying to put the baseUrl in the cypress.json config section to no avail. I can now get some sleep :).

**Comment by susanBuck** [comment]
Ah, yes, my bad, should have said `\tests\e2e\plugins\index.js` - thanks @gaderrick! I'll edit my original post.

And yup, `baseUrl` should be whatever your dev server is running on, whether that be 8080, 8081, etc.

**Comment by susanBuck** [comment]
Updated my original post to use `8080` since that's the more common port. 👍

**Comment by kreinholz** [comment]
Sorry, late to the party, but I can confirm cypress is working on my Windows 10 machine. I start my development server with 'npm run serve', then open a new Cmder tab (Ctrl + T, then click 'Start' to confirm in the dialog that pops up), cd to C:\xampp\htdocs\e28\p4, then launch cypress with:

```
node_modules\.bin\cypress.cmd open
```
I too used 8080 as my baseUrl port. 👍

Thank you @mrtyson93, @gaderrick, and @susanBuck for paving the way!
