### ISSUE TITLE
Extensions in VSCode

### ISSUE THREAD

**Issue by madushag** [susanBuck/e28-fall19#149]
Hi @susanBuck  - do you have a set of extensions you use in VSCode that are recommended as "should-haves" when building apps using Vue? (e.g. Vetur)

**Comment by susanBuck** [comment]
Hi @madushag, Vetur is the primary one.

Another one I find useful for JS apps in general: 
https://marketplace.visualstudio.com/items?itemName=wix.vscode-import-cost
