### ISSUE TITLE
Problem with javascript sets (and I guess other collections)

### ISSUE THREAD

**Issue by ihimawan** [susanBuck/e28-fall19#15]
I was trying to work with javascript Sets by using JSON objects as its elements. But when I tried to do `.has(x)` where `x` is a JSON that I know exists in the Set, it would always return `false`. I guess it makes sense because TIL `{x:1, y:1} === {x:1, y:1}` returns `false`. So my guess is that javascript sets only work on primitives? I was using sets for its `O(1)` lookup (at least that's what I assume javascript has for its Set performance, in the mozilla docs it didn't explicitly say this) 

So then the solution I came down to was doing a `JSON.stringify()`. But that means you need to pay attention to the ordering of the keys.I don't now if there is a better solution for this that guys might have more insight on?

**Comment by coinshot** [comment]
There are many answers on this on StackOverflow, check [this one](https://stackoverflow.com/a/1144249/3855345) for example.
Also, there is a package called [ json-diff](https://github.com/andreyvit/json-diff) that I like (there are also other packages similar to this).
I hope it helps.

**Comment by extra808** [comment]
Yes, I don't think there's a simple comparison of JavaScript objects. If you're using JSON.stringify() just for comparison purposes, a hacky solution would be to split the string to each character `.split('')` as an array, sort the array, and join the array elements back into a string.

I don't know what the objects are you're comparing but an alternative is to write a custom function that compares each part of the objects. Since you want the whole thing to match, comparisons can stop as soon as a part does not match.

**Comment by rokmesojedec** [comment]
it would be helpful if you posted a code snippet of what you're working on.

**Comment by ihimawan** [comment]
@coinshot @extra808  thanks for the responses! The object is just a simple x y coordinate. 
```json
{
  x:1,
  y:2
}
```
I just thought that javascript automatically knew how to compare between two objects (check the fields and then the values and see if they are the same) but apparently not, which is mind boggling for me. My solution to this problem is just to do `JSON.stringify()`

**Comment by coinshot** [comment]
If you wanted to do something simple for when the order of the elements is different, do a simple for loop, something like this:

```
let compare = (a,b) => {
    for (let i = 0; i < Object.keys(a).length; i++) {
        if(!b[Object.keys(a)[i]] || b[Object.keys(a)[i]] != a[Object.keys(a)[i]]) return false
    }
    return true
}
```

Then you can do `compare(a,b)` when a and b are single-level objects, and this is not perfect in any way, but better than simple comparison perhaps.

**Comment by susanBuck** [comment]
I think `JSON.stringify()` is a good solution. 👍

**Comment by terichadbourne** [comment]
@ihimawan I see why `JSON.stringify()` won't work if you need to anticipate the order of the keys changing. 

```js
let a = { x:1, y:2 }
let b = { y:2, x:1 }

JSON.stringify(a) === JSON.stringify(b) //false
```

Note, however, that you can reference keys by their names in JavaScript objects regardless of order, so you could examine `a.x` or `a['x']` directly if it helps, assuming you'll already know the names of those keys. (This is the same concept as @coinshot suggested, just stripping away some of the function and looping syntax in case anyone finds it helpful.)
```js
a.x === b.x && a.y === b.y //true
a['x'] === b['x'] && a['y'] === b['y'] //true
```

**Comment by ihimawan** [comment]
@terichadbourne Yeah that is true. However, luckily I don't expect the key to ever be out of order; so I think stringify should be just fine for this use case.
