### ISSUE TITLE
The peer review

### ISSUE THREAD

**Issue by coinshot** [susanBuck/e28-fall19#151]
I am nearly finished with my peer review. The description for the peer review is pretty clear, and I watched the lecture where it states that some questions may not require extensive answers.

Only on a few of my answers, I am not finding them worthy to be called "Exceptional quality". I have been through the code of the assigned student and read it all, tested the code and tried on various browsers and devices, but still some of the questions are not really applied to them since there is nothing really incorrect with the code, at least not with what matters in the context of this course. So some of my answers are reduced to short sentences. I can add some personal preferences in the comments and explain how I would do what they did, for example, "I would use arrow functions here" and such, but I am not sure if it is appropriate for me to assess their way of doing things as long as, technically speaking, there is nothing wrong with how they did it. 

So wrt the rubric, is there any last suggestion on how to approach questions that are ended up being answered by a yes or no? For the purpose of showing that I have spent enough time on the task, I can write a brief description of my observation, would that be a good approach in such cases/questions?

**Comment by susanBuck** [comment]
It's okay if some/several of the questions are short sentences and even yes/no's; as long as *all* your answers aren't terse.

It's also okay for you to share your personal preferences, with some context on why it's your preference. 

>> I can write a brief description of my observation, would that be a good approach in such cases/questions?

Yup!

For reference, most students end up earning the 10/10. It's only when it's clear student really didn't put any attention into it that it'll earn < 10.

**Comment by coinshot** [comment]
Gotcha. Thank you, @susanBuck
