### ISSUE TITLE
issue with first().click()

### ISSUE THREAD

**Issue by mourad1974** [susanBuck/e28-fall19#153]
Hi,
when I'm looking for the click through;

cy.get('[data-test="product-name"]').first().click()

I get this message

![Screen Shot 2019-11-27 at 4 04 28 PM](https://user-images.githubusercontent.com/35425870/69759301-c71e2c80-112f-11ea-84f2-41da5afedfc8.png)

any idea?

**Comment by coinshot** [comment]
Do you have transition or something on the element that keeps it hidden or not available at that time you fire the test? 

Also I believe you can have something like this in Cypress:

` .click({ force: true })`

This should fix it I hope.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mourad1974** [comment]
Thank you,  that was very helpful, it solved the problem. you are amazing for the help you give

**Comment by coinshot** [comment]
Glad to help, @mourad1974 !

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
