### ISSUE TITLE
PUT or POST requests to Firebase

### ISSUE THREAD

**Issue by kreinholz** [susanBuck/e28-fall19#155]
I know we're going to cover form validation in Week 13, but wanted to ask whether we'd get into saving data to Firebase as part of the course materials.

I've looked at Firebase's documentation:

<https://firebase.google.com/docs/database/rest/save-data>

But so far am having difficulty saving Vue form data using either the PUT or POST methods. Just wondering if we were going to go that far into Vue forms in the Week 13 lesson materials so I can focus my efforts this weekend someplace else (i.e. writing unit and e2e tests for my app).

If saving data to Firebase is beyond the scope of what we're going to cover in Week 13, that's fine, I just wanted to know if I was wasting time/effort troubleshooting an issue we're going to learn the schoolhouse answer to in less than a week. (Because I _definitely_ have other p4-related work I can focus on).

Maybe this can be the start of a thread for those of us who want to add the capability to save/persist data via Firebase to our app.

**Comment by susanBuck** [comment]
I'll cover persisting data to Firebase in Week 13 👍

**Comment by kreinholz** [comment]
Thank you @susanBuck! Made my day!

Guess I’ll be writing tests this afternoon! 😉
