### ISSUE TITLE
Custom "data-test" tag vs using ids for testing

### ISSUE THREAD

**Issue by cgloge** [susanBuck/e28-fall19#156]
Hi there,

I'm still pretty new to implementing unit and integration tests, so I might be missing something obvious, but I was wondering if it would be ok to use an HTML element's id for checking whether or not something loaded / rendered correctly in a test. 

I can see how something like the custom "data-test" tag should be used instead of CSS classes for items which repeat on the page, but I feel like the targeting of those tags is a bit long 
 and awkward.

Thanks in advance for your advice!

**Comment by susanBuck** [comment]
Hi @cgloge - Yup, you can target by ID as well. Any selector (id, element, class, attribute, etc.) will work.
