### ISSUE TITLE
localStorage is not defined error in unit test

### ISSUE THREAD

**Issue by ibrodsk76** [susanBuck/e28-fall19#157]
My child component is using localStorage, and when I try to unit-test it, I'm getting the error "localStorage is not defined". I was able to work around this in a child component by hiding the localStorage into a computed property, and then overriding it in my unit test, as shown in the lecture. But then I try to mount-test the parent component, and I'm back to the same error. Are there any tricks for using localStorage in a unit test?

**Comment by extra808** [comment]
Since localStorage is a browser feature and unit tests don’t use a browser, maybe leave localStorage to E2E tests.

**Comment by susanBuck** [comment]
Confirming @extra808's answer. 

On a side note - running into issues like this tends to reveal things about our code. In this instance, it reveals the component is tightly coupled to (i.e. dependent on) local storage, and it might make us rethink how the component is written. For example, maybe it would be better if the local storage interaction was abstracted to a class (kind of like how I did in Cart.js), which could then be mocked for testing purposes.

Not saying you need to do this - E2E testing of the component is sufficient for our purposes. Just wanted to throw this out there as a factor to consider in code design.

**Comment by ibrodsk76** [comment]
OK, thank you both.
