### ISSUE TITLE
cy.visit() resets Vuex store

### ISSUE THREAD

**Issue by gaderrick** [susanBuck/e28-fall19#159]
All,

Has anyone figured out how to persist the Vuex Store across tests with Cypress? It appears to be wiping the Store back to the default with every `cy.visit()` command. I found something that solves the issue for the localStorage, but haven't found anything for the Store.

**Comment by gaderrick** [comment]
Ok, I needed to change my mindset on this. I lost focus that cypress is testing "from the user perspective." Modified the code to navigate to the link with a click event and everything works.

**Comment by susanBuck** [comment]
Yup! When you do `cy.visit()`, it's the equivalent of the user typing in the URL and re-loading the page - and as a result the Vuex store is reset.

If you have cypress click a link, though, it's just navigating within the SPA without a page refresh, so the Vuex store is persisted.
