### ISSUE TITLE
redirecting routes to error pages

### ISSUE THREAD

**Issue by asalkey** [susanBuck/e28-fall19#160]
If we did cover that can someone tell me which week's video the lesson was in?

**Comment by susanBuck** [comment]
Nope, we didn't see a specific example of this.

Are you thinking of something like this: https://router.vuejs.org/guide/essentials/history-mode.html#caveat ?

I'll work that into ZipFoods for a demo.

**Comment by susanBuck** [comment]
ZipFoods updated with demo. Relevant files:
+ [src/main.js](https://github.com/susanBuck/e28/blob/master/zipfoods/src/main.js#L34)
+ [src/components/pages/NotFoundPage.vue](https://github.com/susanBuck/e28/blob/master/zipfoods/src/components/pages/NotFoundPage.vue)

In action: <https://zipfoods.hesweb.xyz/asdf>
