### ISSUE TITLE
Using Vuelidate library

### ISSUE THREAD

**Issue by coinshot** [susanBuck/e28-fall19#162]
@susanBuck I had implemented a custom field-by-field and overall validation into the form within my project. My validation has messages and it is changing the border and color of the fields on errors. So in my case, do I have to necessarily implement _Vuelidate_ library with regards to the project 4 criteria, or as long as my custom validation functions with no errors and works fine I am fine with keeping it?
 
PS — I can make an arbitrary field somewhere and use the _Vuelidate_ library if it is mandatory.

**Comment by susanBuck** [comment]
Hi @coinshot - Yup, I'll accept that as meeting the validation requirements.

**Comment by coinshot** [comment]
Thank you @susanBuck !
