### ISSUE TITLE
Weired Firebase link

### ISSUE THREAD

**Issue by mourad1974** [susanBuck/e28-fall19#163]
When I create a database in Firebase it gives me a weird link with some alphabets and number that didn't enter like the example below "cdc97" and it works fine then after 10 min or so my application can't retrieve data anymore, till I create a new one and so on.

https://newp4-cdc97.firebaseio.com/)

also, I get this message in the console:
![Screen Shot 2019-12-07 at 11 25 38 AM](https://user-images.githubusercontent.com/35425870/70377609-596ac100-18e4-11ea-8de3-2fa4f420b685.png)

**Comment by coinshot** [comment]
Are adding the "/product.json" to the end of your URL? 
So you basically should fetch this: [http://p4-e28.firebaseio.com/products.json](http://p4-e28.firebaseio.com/products.json)

It loads up fine in the browser.

**Comment by mourad1974** [comment]
> Are you adding the "/product.json" to the end of your URL?
> So you basically should fetch this: http://newp4-cdc97.firebaseio.com/products.json
> 
> It loads up fine in the browser, but it's empty. The name "product.json" can be different based on what you have in the JSON file you upload, for example in the screenshot below I have "items" and "reviews" so I can fetch something like: http://p4-e28.firebaseio.com/items.json
> <img alt="Screen Shot 2019-12-07 at 3 11 47 PM" width="964" src="https://user-images.githubusercontent.com/54965172/70380112-2afcde00-1904-11ea-9d69-67522c139853.png">

**Comment by mourad1974** [comment]
Thank you @coinshot f, Yes I already included  /products.json, for some reason the problem is solved without doing anything, maybe cache issue, I appreciate your help
