### ISSUE TITLE
Zipfoods Cypress tweaks needed after allowing new product creation

### ISSUE THREAD

**Issue by terichadbourne** [susanBuck/e28-fall19#164]
I just finished watching and following along with the form validation segment segment of the Week 13 videos, so I now have the ability to add new products to the listings. As noted in an earlier video, the order in Firebase is no longer consistent, so the previously predictable number and order of product listings can no longer be depended on. 

I found three spots where this broke the E2E tests once I added new products, and I think I've found workaround test methods, but I'd love to hear if someone has better testing ideas for these. (A and B are exactly the same concept/solution, looking for a specific length of a list that's growing, just in different contexts.)

Note that the line references below are to `zipfoods/tests/e2e/specs/zipfoods.js` as of @susanBuck's code after Week 13 Part 2, the last time the file was updated. (Full file at that state [here](https://github.com/susanBuck/e28/blob/c3f948bed0a6d5826c461c240f48ebb66eee5348/zipfoods/tests/e2e/specs/zipfoods.js).) 

**A) In checking that all products appear** ([line 38](https://github.com/susanBuck/e28/blob/bfc24d864f71d19dcc21e05f8cf32cc7d95682e1/zipfoods/tests/e2e/specs/zipfoods.js#L38)): 
```js
cy.get('[data-test="product-name"]').should('have.length', 10)
```
If the number of products will only ever increase as the database grows, and never decrease, then this test seems to work instead: 
```js
cy.get('[data-test="product-name"]').should('have.length.greaterThan', 9)
```

**B) In checking that the categories appear** ([line 62](https://github.com/susanBuck/e28/blob/bfc24d864f71d19dcc21e05f8cf32cc7d95682e1/zipfoods/tests/e2e/specs/zipfoods.js#L62)): 
```js
cy.get('[data-test="category-name"]').should('have.length', 8);
```
If the number of categories will only ever increase as the database grows, and never decrease, then this test seems to work instead: 
```js
cy.get('[data-test="category-name"]').should('have.length.greaterThan', 7);
```
[C) In clicking the first product link on the products page to ensure it renders the right data](url) ([line 43](https://github.com/susanBuck/e28/blob/bfc24d864f71d19dcc21e05f8cf32cc7d95682e1/zipfoods/tests/e2e/specs/zipfoods.js#L43))

In this case the strawberries are no longer first, and we can't seem to control their order in Firebase (although we could choose to sort on display if we wanted), so the strawberries are no longer first in my list, and Cypress clicks the first link and finds another product in its place. 
```js
 cy.get('[data-test="product-name"]').first().click();
```
This replacement test looks for and clicks on the strawberries regardless of where they are in the list: 
```js
cy.contains('[data-test="product-name"]', product.name).click()
```

**Comment by susanBuck** [comment]
Thanks for sharing this @terichadbourne! 

I also reworked the tests (more details here: https://github.com/susanBuck/e28-fall19/issues/166) and skimming through your notes, it looks like our solutions are pretty similar. 👍

```js
// Confirm we see at least 10 products (that's how many product seeds we have)
cy.get('[data-test="product-name"]').its('length').should('be.gte', 10);

// With seed data, we should have at least 8 categories
cy.get('[data-test="category-name"]').its('length').should('be.gte', 8);

// Confirm we can click on a product and get to its individual page
cy.get('[data-test="product-name"]').contains(product.name).click();
```
