### ISSUE TITLE
script variables can't access data inside export default?

### ISSUE THREAD

**Issue by kreinholz** [susanBuck/e28-fall19#171]
I know this is an incredibly silly question, and feel that I'm making a very rookie mistake, but I'm also pulling my hair out over this. Using zipfoods as an example, I have created an object to represent a new comment on a blog post that corresponds to form data within my template:

```js
if (process.env.NODE_ENV == 'development') {
  blogComment = {
    name: 'Kevin Reinholz',
    comment: 'What an amazing blog post!',
    date: JSON.stringify(new Date()),
    postId: this.blogPostId
  };
```
Inside my export default..., I have both a prop and a new variable in data grabbing that value from my prop passed down to the child component:

```js
export default {
  name: 'WriteComment',
  props: ['postId'],
  data: function() {
    return {
      blogComment: blogComment,
      formHasErrors: false,
      blogPostId: this.postId
    };
  },
```
Unfortunately, I get an error that 'blogPostId' is undefined. I strongly suspect it's because I'm trying to access a variable from inside my export default... outside of it, albeit still within the same SFC script section. Any idea how to make that data globally accessible so I can add it to my JS object? I don't want this to be a fillable form data item, I want it to be auto-populated based on what post the user is on...

**Comment by susanBuck** [comment]
What if you move the definition of `blogComment` into a `mounted` method? That way you'll have access to `this.blogPostId`.

For reference, here's an example if I moved the definition of `product` into `mounted` in ZipFoods:

![image](https://user-images.githubusercontent.com/237711/70820367-7dc41300-1da6-11ea-92ab-983d85a48058.png)

**Comment by kreinholz** [comment]
Thank you! That’s brilliant! I figured it would be an easy fix, but the “fog of war” as the project4 deadline looms was making it hard to see my way through the forest. Thanks for the very quick response! 😊

**Comment by susanBuck** [comment]
np! : )

**Comment by kreinholz** [comment]
So, I actually ended up going about this a bit differently, due to placing the blocks of code inside of 'mounted' destroying reactivity with the form, which was sub-optimal. I instead did the following, and am happy to report I am now able to save/write new comments to blog posts to Firebase and retrieve/display them on my blog app:

```js
export default {
  name: 'WriteComment',
  props: ['postId'],
  data: function() {
    return {
      blogComment: {
        commenter: '',
        body: '',
        date: null,
        postId: null
      },
      formHasErrors: false,
      blogPostId: this.postId
    };
  },
```
And then update the 2 fields I want populated automatically under methods:

```js
methods: {
    handleSubmit: function() {
      if (!this.formHasErrors) {
        // Update the date and postId fields within the new comment object
        this.blogComment.date = new Date();
        this.blogComment.postId = this.blogPostId;
```
Before performing an axios request and submitting the comment to Firebase.

**Comment by susanBuck** [comment]
> placing the blocks of code inside of 'mounted' destroying reactivity with the form

Hm, I'm not sure why that would be... In my example I initialized `product` as a data option, and then in mounted I just updated that data option (via `this.product`). It should all still be reactive.

Regardless, I'm happy you landed on a solution that works for you. : )
