### ISSUE TITLE
Axios content doesn't display on first page load with Netlify hosted app

### ISSUE THREAD

**Issue by cgloge** [susanBuck/e28-fall19#174]
Hi everyone,

I hope your semester is wrapping up nicely! Curious if anyone has ideas on this...

I've been able to deploy [my project](
https://p4.boopboop.io/) on Netlify, but I'm running into an issue where my Json content from https://my-json-server.typicode.com/ doesn't load when I visit the page for the first time. 

If I navigate to another page in the app and then come back to it, it does load. Any ideas on what's happening here?

Thanks,
Carly

**Comment by gaderrick** [comment]
What's your github link? I have a hunch that the page/DOM is rendering before the JSON file loads. I had something similar happening, and I basically added a boolean after the json call (setting it to true)  and then added a v-if (or v-show) to the <div> tag that relied on the json data.

**Comment by cgloge** [comment]
That solved it. Thank you so so much for your help!
