### ISSUE TITLE
Netlify error:

### ISSUE THREAD

**Issue by vanillacandy** [susanBuck/e28-fall19#175]
Hi
I tried to deploy static website to netlify by following the video, but got the following error:

2:04:01 PM: Build ready to start
2:04:03 PM: build-image version: 9cade8af58c2cf3a17a1e9433d2e979149488837
2:04:03 PM: build-image tag: v3.3.5
2:04:03 PM: buildbot version: 2d05064ce3dd2eb95d282a24602ab707dd9581e8
2:04:03 PM: Fetching cached dependencies
2:04:04 PM: Failed to fetch cache, continuing with build
2:04:04 PM: Starting to prepare the repo for build
2:04:04 PM: No cached dependencies found. Cloning fresh repo
2:04:04 PM: git clone https://github.com/vanillacandy/e28
2:04:05 PM: Preparing Git Reference refs/heads/master
2:04:05 PM: Error checking out submodules: fatal: No url found for submodule path 'e28' in .gitmodules
2:04:05 PM: Failing build: Failed to prepare repo
2:04:05 PM: failed during stage 'preparing repo': Error checking out submodules: fatal: No url found for submodule path 'e28' in .gitmodules
: exit status 128

**Comment by gaderrick** [comment]
Did you add the following to your netlify build command?

`cd p4 && npm install && npm run build`

**Comment by vanillacandy** [comment]
Yes, I made sure to add those two things

**Comment by gaderrick** [comment]
You're missing the _redirects file in `/public` that needs:

`# Netlify settings for single-page application`
`/*  /index.html 200`

Not sure if that's it, but definitely would impact the url resolution.

**Comment by vanillacandy** [comment]
Hi,
I added the file: 
https://github.com/vanillacandy/e28/blob/master/p4/public/_redirects
But I still got the error: 

2:51:25 PM: Build ready to start
2:51:27 PM: build-image version: 9cade8af58c2cf3a17a1e9433d2e979149488837
2:51:27 PM: build-image tag: v3.3.5
2:51:27 PM: buildbot version: 2d05064ce3dd2eb95d282a24602ab707dd9581e8
2:51:27 PM: Fetching cached dependencies
2:51:27 PM: Failed to fetch cache, continuing with build
2:51:27 PM: Starting to prepare the repo for build
2:51:27 PM: No cached dependencies found. Cloning fresh repo
2:51:27 PM: git clone https://github.com/vanillacandy/e28
2:51:28 PM: Preparing Git Reference refs/heads/master
2:51:29 PM: Error checking out submodules: fatal: No url found for submodule path 'e28' in .gitmodules
2:51:29 PM: Failing build: Failed to prepare repo
2:51:29 PM: failed during stage 'preparing repo': Error checking out submodules: fatal: No url found for submodule path 'e28' in .gitmodules
: exit status 128

**Comment by gaderrick** [comment]
Did you clone or copy your p3 folder to make the p4 project?

**Comment by vanillacandy** [comment]
Yes

**Comment by vanillacandy** [comment]
I copy my p3 folder and make the p4 project

**Comment by gaderrick** [comment]
I see something else that might be confusing netlify in your github. If you look at your repo at: `https://github.com/vanillacandy/e28` there is an additional folder (or something) listed for `e28`, but it isn't clickable so it might be empty.

Do you know what this is? Is it needed?

**Comment by gaderrick** [comment]
Hi-

Yes, I think it is the extra e28 folder in your repo. I downloaded your repo, extracted out the p4 folder and successfully deployed it to netlify. 

Check here: https://modest-murdock-0cef97.netlify.com/

**Comment by vanillacandy** [comment]
Thank you! It fixed the issue by removing the folder.
