### ISSUE TITLE
Sufficient to use Vuelidate on a radio w/ no form submission?

### ISSUE THREAD

**Issue by terichadbourne** [susanBuck/e28-fall19#176]
When I think about form validation, I usually envision a full form filled out and submitted by the user, as we'd need if we wanted to add write functionality to our databases. However, form validation with Vuelidate is required for P4 and write functionality isn't. I've been brainstorming ways to apply it without writing data - since I'm not yet sure whether I'll have time to move my database to Firebase and implement writes. 

Here's what I've come up with so far... running Vuelidate on a radio input that's used by the user to swap between a full list versus a list of favorited items. If the user has selected the "filtered by favorites" view when no favorites exist, Vuelidate creates a message explaining that there's nothing to view. 

I had previously implemented the same functionality using standard v-if statements, but I've moved this logic into Vuelidate. (Here's [the commit](https://github.com/terichadbourne/e28/commit/12066390c010f869d9a05316e9022a2866a0ab4b) that swaps it out to implement Vuelidate.) Is this sufficient to meet project requirements if needed @susanBuck?

**Comment by susanBuck** [comment]
Yup, that's sufficient!

**Comment by terichadbourne** [comment]
Great, thanks for confirming!
