### ISSUE TITLE
SSL cert error on Netlify

### ISSUE THREAD

**Issue by madushag** [susanBuck/e28-fall19#179]
Is this normal for sites hosted on Netlify, unless I deploy my own cert?

![image](https://user-images.githubusercontent.com/40742475/71112352-4506ae00-2199-11ea-85b2-fb03401ee818.png)

**Comment by gaderrick** [comment]
It takes it a little while to provision the SSL certificate. Give it an hour (should take less).

**Comment by susanBuck** [comment]
@gaderrick Is correct! Working now in my tests: https://p4.mydegreestuff.com
