### ISSUE TITLE
Interesting behavior of JSFiddle

### ISSUE THREAD

**Issue by gaderrick** [susanBuck/e28-fall19#18]
All-
I ran into an issue where my game worked in my local environment and failed to run as a JSFiddle app. I finally came across a setting in JSFiddle that needs to be changed in order for "non-global" JS functions to cooperate with how JSFiddle "implements" its code generation. While I don't totally understand the error yet, it appears to be related to the order in which a page is loaded/rendered. See the below image for the setting you may need to change if your JS fails to run (load type):

![fiddle_caveat](https://user-images.githubusercontent.com/10541760/65005402-5784f900-d8c5-11e9-843b-ffd0d7252fae.PNG)

**Comment by susanBuck** [comment]
Good tip, thanks for sharing @gaderrick!

**Comment by nnoel2626** [comment]
I was having the same issue where my word game works fine locally and in code pen but does not work in JSFiddle
