### ISSUE TITLE
Can you please set P4 in Canvas to allow multiple attempts?

### ISSUE THREAD

**Issue by terichadbourne** [susanBuck/e28-fall19#180]
I just submitted my P4 early at an MVP state to avoid spacing out at 11:59pm and submitting nothing, but I was hoping to continue adding features today and resubmit. @susanBuck would you mind enabling the "multiple attempts" feature for this one to make that possible? (Or can I email you a link to my latest commit before midnight?)

**Comment by susanBuck** [comment]
Hi @terichadbourne - you can just email me the latest link when you’re done.
