### ISSUE TITLE
Lodash causing error when trying to set up unit or e2e tests

### ISSUE THREAD

**Issue by conbainbridge** [susanBuck/e28-fall19#181]
Sorry this question is coming so close to the deadline!

When I try to set up unit or e2e testing, I get the following error involving lodash. Is there something I'm missing? I use it in my store index.js file and as far as I can tell it works fine other than this error (the underscore is added to the package.json eslintConfig globals).

```
✔  Successfully installed plugin: @vue/cli-plugin-e2e-cypress


🚀  Invoking generator for @vue/cli-plugin-e2e-cypress...
⠋  Running completion hooks...error: '_' is assigned a value but never used (no-unused-vars) at src/main.js:10:7:
   8 | import Vuelidate from 'vuelidate';
   9 | 
> 10 | const _ = require('lodash')
     |       ^
  11 | 
  12 | Vue.use(Vuelidate);
  13 | Vue.use(VueRouter);


1 error found.
```

**Comment by gpunzalan18** [comment]
Make sure that you declare it as a global variable in package.json:
```
"eslintConfig": {
        "globals": {
            "_": true
        }
}
```

And add the comments below when you define it:
```
/* eslint-disable no-unused-vars */
const _ = require('lodash');
/* eslint-enable no-unused-vars */
```

Here are the [notes](https://hesweb.dev/e28/notes#/vue/writing-to-the-server) from class as a refresher.

**Comment by conbainbridge** [comment]
Thank you so much, I missed that the comments around the const declaration served a purpose!
