### ISSUE TITLE
Project 1 - Question

### ISSUE THREAD

**Issue by claudiomanuelboston** [susanBuck/e28-fall19#23]
I am writing a vue.js and .css file and a index.html.

Are we allowed to include external resource like in the index.html
**http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'** 
as well?

Thanks
Claudio

**Comment by fergus588** [comment]
Does project1 have to contain Vue.js?
Thankyou, Fergus

**Comment by claudiomanuelboston** [comment]
@fergus588 Of course

**Comment by susanBuck** [comment]
@claudiomanuelboston - Yes, external resources/CDN's are ok - that's how I load Vue.js in the Week 3 example. 

However, note that the project should *not* use jQuery (not sure if the URL you provided was just for example, or if you planned on using jQuery, but just wanted to be clear :-)

@fergus588 - Yes; ref: https://hesweb.dev/e28/projects/1

>> Project 1: Basic Vue.js app

>> For your first project, you will create a game similar to the one you created in the Week 2 assignment, this time using Vue.js.
