### ISSUE TITLE
Vue is not defined

### ISSUE THREAD

**Issue by pingji00** [susanBuck/e28-fall19#24]
Hi, 

I tried to follow the tutorial of Week 3, Part 2 to do the same demo on my local environment but wasn't able to repeat it. The error is "Vue is not defined".

Attached is the screenshot to show the console warning. Any suggestions would be appreciated. 

Thank,
Ping

<img width="1052" alt="Screen Shot 2019-09-20 at 9 41 44 AM" src="https://user-images.githubusercontent.com/12189712/65331465-e1b1b380-db8a-11e9-93fa-6f2548bf9b06.png">

<img width="1051" alt="Screen Shot 2019-09-20 at 9 41 21 AM" src="https://user-images.githubusercontent.com/12189712/65331466-e1b1b380-db8a-11e9-8a30-3b60f08e6891.png">

**Comment by rokmesojedec** [comment]
Add the `defer` attribute on the script tag referencing script.js

**Comment by pingji00** [comment]
Aha, forgot that. I've never tried to put the script in the header before. 
Thank you so much!!
