### ISSUE TITLE
Mac users - Updated .basrc template for Terminal

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e28-fall19#25]
In the [Mac Terminal](https://hesweb.dev/e2/notes#/command-line/mac-terminal) notes, I explain how your Terminal can be customized, and I provide a template `.bashrc`you can use for those customizations.

I recently identified a bug in this template that caused weird text wrapping issues in Terminal. When lines of text extended past the window, they wrapped over on themselves instead of going to the next line.

The bug has been fixed; here's a link to the updated [.bashrc template](https://gist.github.com/susanBuck/ee3a0a53d72198c1a244).

If you followed along in editing your own `.bashrc` file, you should update it to match the fixed template. Don't forget to save any aliases you might have created before replacing.

If you never customized Terminal, you don't have to do anything.

Hat tip to @terichadbourne for leading me to the source of the issue! (ref: #21)

**Comment by pausman** [comment]
alias htdocs='cd /Applications/MAMP/htdocs' 
needs to be
alias htdocs='cd /Applications/XAMPP/htdocs'

**Comment by susanBuck** [comment]
Thanks @pausman - Corrected.

**Comment by apatruno618** [comment]
Thank you, this is super helpful. Luckily just expanding the window helped but that issue was driving me crazy!

**Comment by tedsirota** [comment]
Same here ^^ Thanks!
