### ISSUE TITLE
CDN resources used

### ISSUE THREAD

**Issue by claudiomanuelboston** [susanBuck/e28-fall19#26]
@susanBuck 
I am using the following **standard CDN resource**, but I am not using jquery at all in my code
<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

**Comment by susanBuck** [comment]
Hi @claudiomanuelboston - I'm confused - why include jQuery if you aren't (and shouldn't) use it?

**Comment by claudiomanuelboston** [comment]
I was wrong, I am all set
