### ISSUE TITLE
The Vue developer tool tab is missing

### ISSUE THREAD

**Issue by pingji00** [susanBuck/e28-fall19#27]
I've installed the Vue developer tool in Chrome, but for some reason, it doesn't show up on my Intro practice file. It works for vuejs.org though. Any suggestions?

<img width="1080" alt="Screen Shot 2019-09-20 at 2 48 26 PM" src="https://user-images.githubusercontent.com/12189712/65351526-564e1780-dbb6-11e9-8cd1-177158450ec6.png">

<img width="1082" alt="Screen Shot 2019-09-20 at 2 48 15 PM" src="https://user-images.githubusercontent.com/12189712/65351528-564e1780-dbb6-11e9-9c95-9c4b3b0fc5dd.png">

**Comment by pausman** [comment]
are you loading the script.js with the vue defined in it?

**Comment by coinshot** [comment]
You are probably using the production version of the CDN. Make sure to use the development version in order to use the Vue dev tool.

CDN, The development version: 
`<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>`

**Comment by pingji00** [comment]
Thanks, @coinshot. It works just by quitting Chrom and open it again.
