### ISSUE TITLE
vue not showing up in devtools

### ISSUE THREAD

**Issue by vanillacandy** [susanBuck/e28-fall19#28]
I added  <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js" defer></script> in the code. 
When I opened the devtool console, it shows 
"You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html"

Another message I got in console is: so I went ahead to download the extension.
"Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools" 

But Vue pane isn't showing up in devtools

**Comment by pausman** [comment]
Did you install the chrome extension from the link? https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd

You might have to restart chrome though I don't remember having to.

**Comment by vanillacandy** [comment]
Yes, I did install the extension

**Comment by phildarnowsky** [comment]
Are you looking at a `file` URL or `http`? Extensions aren't allowed access to `file` by default, so if that's the case you would have to right-click on the Vue devtools icon -> click "Manage Extensions" -> turn on "Allow access to file URLs".

**Comment by vanillacandy** [comment]
Thanks, that fixes it.
