### ISSUE TITLE
Windows users - be really, really careful adding to httpd-vhosts.conf

### ISSUE THREAD

**Issue by kreinholz** [susanBuck/e28-fall19#29]
I spent several frustrating hours troubleshooting what I thought to be general XAMPP issues, only to discover that the tiniest of typos while adding [VirtualHost entries](https://hesweb.dev/e28/notes#/local-server/local-domains?jump=step-2-virtualhost-entry) to my **httpd-vhosts.conf** resulted in my Apache server failing to start.

The output from XAMPP led me to believe I might have a port conflict, or one of the more common XAMPP errors noted in the course materials and by Googling. Nope, I had an extraneous space in one of my VirtualHost lines. So, my recommendation is to copy+paste from the linked course guidance above rather than trying to retype it yourself, and make customizations as needed for your purposes. After doing this, I not only noticed the extraneous space issue, but got my Apache server running happily and allowing me to access the suggested virtual domains from Chrome without any problems.

Let my wasted time serve as a cautionary tale!

**Comment by audreychenjj-2019** [comment]
I have the exactly opposite experience. I copied and pasted the code directly from the course guidance and didn't fix all the "format" issues. After step 1 and 2 my server just refuse to start. I read the error log and it said:

```
[Sat Sep 21 01:47:49.284211 2019] [ssl:warn] [pid 17688:tid 732] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
 ```
I then decided to hand typed the code into my **httpd-vhosts.conf** and restarted the server. It worked!

However I agree with you, whichever method one choose, the space and indentation are quite important in setting things correctly in the file.

**Comment by extra808** [comment]
@audreychenjj-2019 that error is regarding www.example.com:443, a virtual server that would require security certificate. Your XAMP install may have included such a sample in `http-vhosts.conf` (mine Mac version doesn't) but it isn't within the [Local domain notes](https://hesweb.dev/e28/notes#/local-server/local-domains).

**Comment by kreinholz** [comment]
@audreychenjj-2019 I'm sorry to hear that! I'm not used to using Windows as my development machine, so it's been quite the adjustment. I normally use **vim** as my console text editor, which works most of the time from **Cmder**, except in conjunction with the "elevate" command or editing the **hosts** file, for which I used **nano**.

After all my frustration re **httpd-vhosts.conf**, I just gave in, used **Notepad,** and then copied+pasted between **Chrome** and **Notepad**. I then made my customizations using **vim** from the command line.

I mostly started this post to help others avoid the same frustration I experienced--finding my Apache server suddenly not working, and chasing a bunch of red herrings rather than focusing on the obvious culprit, the one thing that changed since I set it up (since it was working just fine for Weeks 1 and 2).

I'd be a lot more comfortable on a *nix machine or a Mac, but since I've chosen to set up my Windows laptop as my development machine, us Windows users should stick together as issues arise! There are just a number of small differences, especially with regard to the command line, that make the user experience jarring after coming from a Mac and *nix environment. Once I get into **VS Code** and do actual course-related coding, Windows is just fine. It's mostly the command line that's frustrating after coming from Mac and *nix.

**Comment by andmade** [comment]
@kreinholz 

If you want to set a bit of time aside, you might look into the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/about). I used it to install Ubuntu and then you can have a regular *nix prompt and more or less follow along with the Mac instructions. It took a bit of searching around to get it working properly with Cmder and VS Code, plus a decent color scheme going on for it and `ls` but it seems to be going well so far.

![Screenshot (6)](https://user-images.githubusercontent.com/21956231/65382028-f2694300-dcca-11e9-862b-575134f836ca.png)

**Comment by kreinholz** [comment]
@andmade

Now _that_ looks like a more attractive terminal on Windows! I'm not sure if I'll go that far, although it's nice to know the option exists. Trying to get more familiar/comfortable with Windows as my development environment. I think keeping in mind the text editor and terminal differences, and grinding away at it, my comfort level will get there.

**Comment by nhillsbos** [comment]
Hello! I've tried copying and pasting directly into notepad, but I'm still getting an "object not found" message when I try to load the custom URL. Of course, I am on windows. So far the real challenge has been figuring out what SPECIFIC microscopic changes to make to actually get these things to work.

**Comment by kreinholz** [comment]
@nhillsbos 

This is the line that messed me up:

```Order allow,deny```

I somehow inserted a space between the comma trailing allow and the word deny. That was enough to make **XAMPP** very unhappy.

I recommend going back to a working **XAMPP** baseline and making sure your Apache server can run, then going through [the local domain](https://hesweb.dev/e28/notes#/local-server/local-domains?jump=local-domain) instructions methodically, making and applying one change at a time, and restarting your Apache server to make sure it's still working. That way, you'll be able to pinpoint the precise change that breaks the camel's back, since no error logs were generated for me when I copied the example incorrectly.

Hope this helps!

**Comment by susanBuck** [comment]
Some great tips and insight into this thread! 

I concur with avoiding typing in config related stuff. Copy/paste/edit as needed generally works out best for me. It doesn't eliminate human error, but it does reduce it.

I did some research on the best way to troubleshoot syntax errors in a VirtualHost file and learned that if you invoke Apache from the command line with the `-S` flag, it will show settings as parsed from your VirtualHost file; it will also show you syntax errors!

In XAMPP, we can access Apache from command line via `c:\xampp\apache\bin\httpd.exe`.

Here's an example after I introduced a space error into my VirtualHosts file:

```
λ c:\xampp\apache\bin\httpd.exe -S
AH00526: Syntax error on line 51 of C:/xampp/apache/conf/extra/httpd-vhosts.conf:
order takes one argument, 'allow,deny', 'deny,allow', or 'mutual-failure'
```

Super helpful! I'll be adding this tip to the notes.

Another thing you can do if you're stuck - post the configs you're using here. Use myself and your classmates as a "fresh set of eyes" to catch those little gotchas.


@audreychenjj-2019:
>> I have the exactly opposite experience. I copied and pasted the code directly from the course guidance and didn't fix all the "format" issues. After step 1 and 2 my server just refuse to start

Can you elaborate on the format issues? Were there issues in the original config you copied from the notes, or did it just get messed up when pasting? Regardless, would love to know more details to see if there's something I can fix/optimize on my end.
