### ISSUE TITLE
Unable to access week 1 assignment

### ISSUE THREAD

**Issue by guezandy** [susanBuck/e28-fall19#3]
![Screen Shot 2019-09-07 at 12 14 11 PM](https://user-images.githubusercontent.com/3968674/64479236-06f4f980-d169-11e9-85b8-a9a9625ff960.png)

**Comment by susanBuck** [comment]
Hi @guezandy - I'm not sure why it's showing that for you - I double checked that you were listed as enrolled in both the HES system and Canvas. I can also see that other students have successfully accessed/completed the assignment. 

I'm going to reach out to Canvas support to have them look into this and will report back when I know more details.

In the meantime, I'll email you a copy of the assignment so you can see the material there.

**Comment by susanBuck** [comment]
[Here's a PDF of the assignment](https://s3.amazonaws.com/screenshots001/week1.pdf) (I decided to share it here in case any other students face the same issue)

@guezandy I just spoke with Canvas support and they said to try again.

**Comment by gaderrick** [comment]
@guezandy, I ran into the same error. For me, I had to actually click on the "login" link (in Canvas) to re-login with my Harvard Key. I tried to duplicate the screenshots, but can't get it to repeat the same behavior. Hope this helps.

**Comment by extra808** [comment]
@gaderrick Yes, the "Only registered, enrolled users can take graded quizzes" message appears when one is not logged in to Canvas. I think this can only happen when courses are still open for shopping, after that, I don't think non-logged-in users will be able to get to the assignment pages at all.

**Comment by susanBuck** [comment]
Ah yes, being logged in is required. : )

**Comment by guezandy** [comment]
Thanks team - guess I wasn't logged in? Either way it all works now
