### ISSUE TITLE
Vue.js devtools in Safari

### ISSUE THREAD

**Issue by nnoel2626** [susanBuck/e28-fall19#30]

**Comment by nnoel2626** [comment]
Does anybody know how to install Vue.js devtools in Safari

**Comment by extra808** [comment]
There is no [Vue devtools](https://github.com/vuejs/vue-devtools) extension for Safari, only Chrome and Firefox. There's a standalone Electron app that's supposed to work with any browser but to me it's not worth the trouble.

I like Safari as my default browser so I use that for reading documentation, googling questions, etc. and use Firefox to run my development code.

**Comment by coinshot** [comment]
Try this: https://stackoverflow.com/a/47833848/3855345

**Comment by susanBuck** [comment]
Confirming @extra808's answer. 👍

Check out the [Installation section in their README](https://github.com/vuejs/vue-devtools#installation) for links to the Chrome and Firefox extensions, or the standalone Electron app.
