### ISSUE TITLE
Nano- delete all text?

### ISSUE THREAD

**Issue by mourad1974** [susanBuck/e28-fall19#31]
is there any option to select all text in NANO  file and delete it at once?

**Comment by gpunzalan18** [comment]
I couldn't find a select all. But [this post](https://askubuntu.com/questions/154431/how-do-i-delete-multiple-lines-in-nano-without-affecting-the-clipboard) gives an alternative solution.  I've copy pasted one of the answers below: 

> 1. use `CTRL+Shift+6` to mark the beginning of your block
> 2. move cursor with arrow keys to end of your block, the text will be highlighted.
> 3. use `CTRL+K` to cut/delete block.
>
> To paste the block to another place, move cursor to the position and the use `CTRL+U`. You can paste the block as often as you want to.

I hope this helps!

**Comment by naztronaut** [comment]
If you want to get rid of ALL text, just remove the file and recreate it. `rm filename` then `nano filename` should do the trick.

**Comment by mourad1974** [comment]
thank you @gpunzalan18 @naztronaut , i coudn't selct and delete all text with cmd k on mac os, so where can i find the .bashrc. file to delete it

**Comment by gpunzalan18** [comment]
@mourad1974  make sure you use `CTRL+K` and not `CMD+K`. I also have a mac and tried the solution and it worked fine.

**Comment by mourad1974** [comment]
based on nano documentation 
"-k, --cut
Cut from the current cursor position to the end of the current line."
all I could do is delete one line using CTR k.
 I know how to delete/create files with nano but I'm wondering which folder is the ".bashrc" file?

**Comment by andmade** [comment]
@mourad1974 

On Macs, the .bashrc file is by default located in your home directory. If you placed the template from Susan there or edited it using the commands from the class notes you should be able to delete it with `rm -i ~/.bashrc`. You may need to preface it with `sudo` if you get a permissions error.

**Comment by mourad1974** [comment]
Thank you @all
