### ISSUE TITLE
Declaring methods

### ISSUE THREAD

**Issue by ihimawan** [susanBuck/e28-fall19#35]
I am trying to understand how Vue is working. For the `methods` attribute in the `Vue` constructor,  is there a reason why executing `someFx()` when it is declared this way:

```javascript
methods: {
   someFx: function() {
      this.name = 'someName'
  }
}
```
updates `{{name}}` in the virtual DOM but declaring it as 
```javascript
methods: {
   someFx: () => {
      this.name = 'someName'
  }
}
```
would not even update the `name` in `data` ?

**Comment by coinshot** [comment]
You can simply do it like this:

```
methods: {
   someFx() {
      this.name = 'someName'
  }
}
```

**Comment by susanBuck** [comment]
It has to do with the scope of `this` with traditional function syntax vs. arrow function syntax.

Arrow functions do not define their own `this`; it's inherited from the enclosing scope - in this case, the Vue instance.

With your first example (the traditional syntax), `this.name` is scoped to that particular function.

**Comment by susanBuck** [comment]
Side note for classmates: We haven't talked about Vue methods or ES6 arrow functions yet, so don't be alarmed if you're reading this thread and wondering if you're missing something. :)

**Comment by coinshot** [comment]
I found this a good read: [Clean up your Vue modules with ES6 Arrow Functions](https://gist.github.com/JacobBennett/7b32b4914311c0ac0f28a1fdc411b9a7)

Perhaps wait and read it after Susan explained it later in the course though.

**Comment by ihimawan** [comment]
Thanks @coinshot ! That is an interesting way to do it. I guess it's just really hard for me to grasp that one because my understanding is that `methods` is supposed to be a JSON object (key-value pairs). How is it that `someFx() {...}` satisfies that?

**Comment by ihimawan** [comment]
@susanBuck Hmmm I guess that makes sense. I was also trying to figure out why `this.name` was even accessible in the first place by the non-arrow methods. Is it because `this` would refer to `app.$data`? Whereas the `this` in arrow methods would simply just refer to the create Vue object (`app`) ?

**Comment by coinshot** [comment]
@ihimawan Methods are not JSON objects, they are literraly methods, they are functions that are assigned to that component in Vue.

**Comment by susanBuck** [comment]
@ihimawan - Correction to my last post - I explained it poorly:

In arrow functions, the value for `this` is inherited from its enclosing scope, yes, but the enclosing scope is not the Vue instance (as I mistakenly said) - it's the window. 

You can see this if you you do a `console.log(this);` from within your arrow function.

![image](https://user-images.githubusercontent.com/237711/65472695-be189280-de42-11e9-8e0e-07e5c36e7a80.png)

That more accurately explains why `this.name` in your arrow function has no impact on the Vue instance's `name` property.

**Comment by ihimawan** [comment]
@coinshot hmm interesting. I guess I just have a hard time understanding the `{...}` syntax as something other than a key-value pair. What it sounds like you are saying is `method` is a comma separated value of function definitions. But within curly braces.

**Comment by ihimawan** [comment]
@susanBuck thanks for the example! Got it.. so basically the arrow syntax was accessing the variables from `window` and that was why it wasn't updating the app. Thanks for your help!

**Comment by ihimawan** [comment]
@coinshot  thanks for the explanation!
