### ISSUE TITLE
Vue.js tutorial - not an issue

### ISSUE THREAD

**Issue by claudiomanuelboston** [susanBuck/e28-fall19#36]
Trying to learn more vue.js on my own, I came across this very good tutorial

https://www.taniarascia.com/getting-started-with-vue/

**Comment by susanBuck** [comment]
Thanks for sharing! I agree it's helpful to read about the same info from multiple sources when learning something new. It helps solidify the concepts, and sometimes one tutorial/source will explain things in a slightly different way that might "click" better with you.

**Comment by conc2304** [comment]
Ooh nice!
I was also looking for tutorials to start learning some more vue on my own and have really liked this one https://travishorn.com/getting-started-with-vue-single-file-components-f29765a771a3
