### ISSUE TITLE
PSA: A few useful tips

### ISSUE THREAD

**Issue by atanasgizdov** [susanBuck/e28-fall19#37]
A couple of gotcha's that I worked through last couple of days in case folks run into the same things: 

- On my apache config, I had to enter 'Include etc/extra/httpd-vhosts.conf' by hand from scratch - it did not exist in the vhosts section of the file (at the very end)
- I highly recommend adding dev tools to Chrome. In addition, keep in mind or refresh yourself on how the DOM tree is built and why you may get errors instantiating Vue. I had to go through a few cycles before swapping the order in which I was calling the JS scripts. 
- Finally, JS fiddle is a great resource and I highly recommend using it as a sandbox for quick iteration when working with JS

**Comment by susanBuck** [comment]
Thanks for sharing these tips, @atanasgizdov! 

Can you share a copy of your apache `httpd.conf` file? I'm curious to see what other differences there are between your config and the one I see w/ my XAMPP install.

Couldn't agree more on the Chrome dev tools + JS Fiddle tips. 👍

**Comment by audreychenjj-2019** [comment]
I echo the tip about JS fiddle. It really is very convenient to have all the pieces together in one window.
