### ISSUE TITLE
local domain isn't showing up expected index.html 

### ISSUE THREAD

**Issue by vanillacandy** [susanBuck/e28-fall19#38]
After following the steps to set up local domain, when I tested it by opening the https://intro.loc, it shows only the following one line instead showing up my website. 

Hello from my XAMPP-powered server!

**Comment by pausman** [comment]
It doesn't find a correct entry in your virtual hosts file in /Applications/XAMPP/etc/extra/httpd-vhosts.conf (mac) or  c:\xampp\apache\conf\extra\httpd-vhosts.conf(pc). It is very picky.  I would copy the VirtualHost entry from the notes and edit them to change practice to intro.

**Comment by pausman** [comment]
First try http://intro.loc not https://intro.loc

**Comment by vanillacandy** [comment]
Yes, that fixes it quickly thank you!
