### ISSUE TITLE
Difference about mounting

### ISSUE THREAD

**Issue by audreychenjj-2019** [susanBuck/e28-fall19#39]
While searching for some basic concepts I came across the comparison of these two ways of mounting an instance.

```Javescript
new Vue({
    data () {
        return {
            text: 'Hello, World'
        };
    }
}).$mount('#app')
```

The blow is what we learned. What benefits do we have by mounting this way?
```Javescript
new Vue({
    el: '#app',
    data () {
        return {
            text: 'Hello, World'
        };
    }
})
```

**Comment by coinshot** [comment]
https://stackoverflow.com/questions/46831452/difference-between-mount-and-el-vue-js

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by susanBuck** [comment]
Good reference from @coinshot above ^^^.

You'll see the "el" approach more often. Use the "mount" approach if you need flexibility as to which element you're mounting on.
