### ISSUE TITLE
bash template typo

### ISSUE THREAD

**Issue by pausman** [susanBuck/e28-fall19#4]
In the bash template provided it refers to MAMP rather than XAMPP.

```
# Example alias for quickly getting to a commonly used directory
alias htdocs='cd /Applications/MAMP/htdocs'
```
It should be
```
alias htdocs='cd /Applications/XAMPP\htdocs'
```
The same mistype occurs in the ALIASES section
`https://hesweb.dev/e28/notes#/command-line/mac-terminal?jump=aliases`

**Comment by susanBuck** [comment]
Fixed. Thanks @pausman. (and good to see you in class again :)
