### ISSUE TITLE
Video playlist order

### ISSUE THREAD

**Issue by extra808** [susanBuck/e28-fall19#41]
@susanBuck, rather than clicking [each lecture video link](https://hesweb.dev/e28/week/4) on the week's page, I normally go to your [DMGD E-28 playlist](https://www.youtube.com/playlist?list=PLjP535FLNNlozIpVpTum2OkhUUA-trWRs) on YouTube and let them play through. However, right now the Week 4 parts are ordered 2, 4, 3, 1, 5. If it's easy to reorder the videos in the playlist, that would be appreciated. If not (e.g. it would require re-uploading videos), this is an FYI to anyone else who does what I do.

**Comment by susanBuck** [comment]
Fixed. 

I usually upload the videos as I complete them; as a result, they typically get added to the playlist in order.

This week, I uploaded them all at once and they got ordered by whichever ones uploaded fastest.

I've always just added them to the playlist for the purpose of organizing my videos in my YouTube library - I didn't think/realize students were using it. : )

**Comment by extra808** [comment]
Thanks! If I use the links to each video, I don't think the speed setting is preserved but when I play them from the playlist, it carries over from one to the next.
