### ISSUE TITLE
Can I enter two ssh keys into my Droplet?

### ISSUE THREAD

**Issue by mourad1974** [susanBuck/e28-fall19#43]
Hi everyone
I successfully connected my desktop  to Digital Ocean droplet through first ssh key, I still need to connect my laptop to the same droplet but I don't see the option to enter a second ssh key in Digital Ocean droplet

**Comment by andmade** [comment]
You can do it from your account settings page:

https://cloud.digitalocean.com/account/security

If the above link doesn't work, you can click the upper right icon and select account. Then go to the Security tab to add more SSH keys.

**Comment by naztronaut** [comment]
You can't add news keys to existing droplets through their control panel. That's only used during account creation. 

But you can still add a new keys to existing droplets through command line. If you have generate a new public key, check out this article: https://www.digitalocean.com/docs/droplets/how-to/add-ssh-keys/to-existing-droplet/

You can also just copy your private key from your desktop to your laptop and access it that way. This is a quick and dirty way.

**Comment by susanBuck** [comment]
Confirming @naztronaut's note:

>> You can't add news keys to existing droplets through their control panel. That's only used during account creation.

Here's the approach I would use:

1. Generate a new key pair on your laptop.
2. Get a copy of the generated public key from your laptop to your desktop.
3. SSH into your DO server from your desktop and add your laptops public key to this file: `~/.ssh/authorized_keys`

Now your laptop should be able to SSH in.

**Comment by susanBuck** [comment]
Side note: I do have a supplemental note set on how to get access to your server to add a key:
<https://hesweb.dev/e28/notes#/appendix/permission-denied>

These notes assume you have no existing SSH access though. In your case, because you can SSH in via your Desktop, it's an easier process.

**Comment by mourad1974** [comment]
Thank you, that worked perfect!
