### ISSUE TITLE
Re-using droplets, domains, etc. from E-15

### ISSUE THREAD

**Issue by bibliodrone** [susanBuck/e28-fall19#44]
Hi,

What would be the best practices as far as reusing production servers and domain names from the previous semester (DWA -- E-15)?

I took E-15 last semester, and as a result I already have a production server and domain name in place. The setup is pretty much the same as what is needed for this course. 

Should I create a new droplet for this class, or could I continue to use the existing one? One problem is that I already have p1-p4 domains pointing to E-15 coursework (e.g.: `p1.mydomainname.me`). 

If I create a new droplet, the question would be: are there any problems with continuing to use the existing domain name? Would I just need to point the domain to the new droplet's ip address? 

Either way it seems to require that I make adjustments somewhere (or use a different domain than p1-p4).

Thanks for your help,

Gerry Walden

**Comment by andmade** [comment]
It depends on what you want to do. I simply went into the virtual hosts file and changed the domain to point to the p1 folder for this class. If you want to keep the e15 coursework working, you could do the same thing but then create a new subdomain and virtual hosts config for the e15 work.

**Comment by bibliodrone** [comment]
andmade, 

Thanks for replying. I was thinking along the same lines of adjusting the virtual hosts file. I don't really need the e15 coursework to be up on the internet any longer, so the method you mention seems like the straightforward solution, unless there is some other 'gotcha' I am not aware of. 

I also renamed the GitHub repositories for the old coursework to prevent conflicts there. 

-Gerry

**Comment by susanBuck** [comment]
Totally fine to re-use domain/services from E15.

Agreed with the suggestion of just adjusting the VirtualHosts as needed.

I can't think of any gotchas you should be concerned about. : )
