### ISSUE TITLE
Using a service other than DigitalOcean & using a domain only to fulfill the projects

### ISSUE THREAD

**Issue by coinshot** [susanBuck/e28-fall19#45]
I like DigitalOcean, I am using it for some apps, but I have service from another provider that would be more accessible for me to use for this course purposes, so as long as I properly present my projects as p1.domain.com and so on, would it be acceptable if I do not use DigitalOcean? 

Additionally, I have a domain that I have been using for my school projects, is it acceptable if I just use it for the projects and create subdomains for each project, or we are expected to necessarily have the entire repo cloned on a domain that is entirely designated to this course?

Thank you!

**Comment by susanBuck** [comment]
Yup, it's acceptable to use other services.

I only suggest sticking with the services I cover if you're not comfortable/familiar with the concepts we're covering on these services.

More on this here: https://hesweb.dev/e28/software#Other%20tools%20or%20services
