### ISSUE TITLE
Can't display my sub-domain directories 

### ISSUE THREAD

**Issue by nnoel2626** [susanBuck/e28-fall19#46]
I able to display my "documentRoot" index file in the browser but I am not able to display my sub-directories index files. I was able to ping my subdomain which is pointing my digital ocean e28 droplet IP address. Any help will be appreciated. See attached virtualhost file from Digital Ocean 
[VirtualHost server file.txt](https://github.com/susanBuck/e28-fall19/files/3671271/VirtualHost.server.file.txt)

server.

**Comment by extra808** [comment]
Did you change something? http://game.nnoel.xyz and http://p1.nnoel.xyz load for me.

**Comment by nnoel2626** [comment]
I also sent a ticket to Digital Ocean. I think they fixed whatever that wasn't working. Thanks for checking.
