### ISSUE TITLE
Unable to attach image in Quiz

### ISSUE THREAD

**Issue by vanillacandy** [susanBuck/e28-fall19#5]
In question 2, we are required to post an image, but I didn't find where to attach a snapshot.

**Comment by susanBuck** [comment]
Sorry about that - just corrected it so it's a "file upload" question. You may have to restart the assignment to see the changes.

If for some reason you're still not seeing it, you could upload your image on something like https://imgbb.com and answer the question with a link to that image.

**Comment by extra808** [comment]
A File Upload question type is simpler but you can also upload an image through the WYSIWYG text editor. Click the Embed Image button, switch to the Canvas tab, under Available Folders click My Files, then click the Upload file button.
