### ISSUE TITLE
When are conditional directives evaluated?

### ISSUE THREAD

**Issue by cgloge** [susanBuck/e28-fall19#50]
I'm curious when conditional directives are evaluated. Does Vue.js have some sort of under-the-hood logic that sees if the value of the variable being evaluated for the conditional directive has changed?

I think it's super cool that it re-triggers on change, but I'm trying to figure out how the underlying functionality works? :)

**Comment by extra808** [comment]
Yes, Vue generally "knows" when various data changes; in input fields with [v-model](https://vuejs.org/v2/api/#v-model), it listens for `oninput` events unless modified with `.lazy` which makes it only trigger `onchange` (I don't know if that event ever occurs without `onblur` also happening).

Part of what we covered in List Rendering is Vue only detects changes to arrays (not through the UI) when the [mutation methods](https://vuejs.org/v2/guide/list.html#Mutation-Methods) are used; if you directly assign a new value to an element of an array, Vue won't "know" about it.

**Comment by susanBuck** [comment]
There's a good read in vue docs that digs into the inner workings: [Reactivity in depth](https://vuejs.org/v2/guide/reactivity.html)

Also, here's my summary of the reactivity system: 

> As you saw in the example built in the introduction, when data of our Vue instance is changed, those changes are propagated wherever that data is being used.

> This works because of Vue’s reactivity system, which involves two key ingredients:

> First, Vue keeps track of all the dependencies within an instance.

> For example, if we bind the data property playerName to a text input, that creates a dependency between those two things.

> Second, when the Vue instance is set up, it creates getter/setter methods for each of the data properties we define.

> Getter/setter methods are methods that are automatically invoked when a property is retrieved (getter) or changed (setter).

> The setter method is programmed to update any corresponding dependencies.

> So, if playerName changes, its setter function is triggered, and it will update its dependents - which includes the value of the text input.

ref: https://hesweb.dev/e28/notes#/vue/behind-the-scenes?jump=reactivity-system

Applying this to your specific question - if you had a conditional directive dependent on `playerName` - whenever `playerName` was updated, it would re-evaluate that conditional.

Hope that helps clarify the under the hood "magic" - but let us know if you have any follow-up q's!

**Comment by susanBuck** [comment]
Closing this post due to inactivity, but feel free to continue the discussion or post a new thread if any questions are still pending.
