### ISSUE TITLE
Solution to Permission Denied issue for SSHing into your public DigitalOcean server

### ISSUE THREAD

**Issue by cgloge** [susanBuck/e28-fall19#51]
Hey there,

I was getting a permission denied error when SSHing into my DigitalOcean server. Thought I'd post an article that helped me resolve the issue:

https://www.digitalocean.com/community/questions/permission-denied-after-creating-droplet-using-ssh-keys

Best,
Carly

**Comment by susanBuck** [comment]
Thanks for sharing Carly! There's lots of suggestions in that post - curious which one did the trick for you?

Also, for reference, here's a supplemental note set I have that also talks about the *Permission Denied* error: https://hesweb.dev/e28/notes#/appendix/permission-denied

**Comment by cgloge** [comment]
Sorry! I should have added that clarity. Here's the one that worked for me:

```
eval `ssh-agent -s`
ssh-add ~/.ssh/id_rsa 
ssh root@xxx.xxx.xx
```

**Comment by susanBuck** [comment]
Great, thanks again for sharing!
