### ISSUE TITLE
Data property not being recognized by Vue instance

### ISSUE THREAD

**Issue by apatruno618** [susanBuck/e28-fall19#52]
I added results to the data property as described in lecture, saved my changes, restarted my server, and refreshed my browser but it is still not being recognized by the Vue instance:

The script.js:
```javascript
let app = new Vue({
    el: '#app',
    data: {
        'playerChoice': null,
        'shapes': ['rock', 'paper', 'scissors'],
        'computerChoice': null,
        'result': 'tie'
    },
```

The html:
```html
    <p v-if='result == "tie"'>It's a tie!</p>
    <p v-else-if='result == "win"'>You win!</p>
    <p v-else>You lost, boo!</p>
```

I just keep getting this error:
```
[Vue warn]: Property or method "result" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

(found in <Root>)
```

**Comment by gpunzalan18** [comment]
Can you try to use `cmd + shift + r` to refresh the browser? 

I was having the same issue and learned that the old version of my code is being cached in the browser. `cmd + shift + r`  overrides it.

**Comment by apatruno618** [comment]
That worked, thank you!!! I just kept refreshing with cmd + r thinking that was giving the browser a hard refresh.
