### ISSUE TITLE
VS Code JavaScript

### ISSUE THREAD

**Issue by audreychenjj-2019** [susanBuck/e28-fall19#53]
I'm using VS Code for writing my codes since it's easier for me to follow Susan's examples.

However every time when I create a new Vue instance, VS Code will automatically fill in 

```JaveScript
new VTTCue()
```
and I end up manually changing *VTTCue()* to *Vue()*.

Any idea why this happens?

**Comment by susanBuck** [comment]
In your settings, toggle `Editor: Accept Suggestion On Commit Character` off, but leave `Editor: Accept Suggestion On Enter` on.

![image](https://user-images.githubusercontent.com/237711/66088895-f0b14200-e54a-11e9-986c-c003b8f770e6.png)

This way it will only accept suggestions when you hit enter, not when you enter a commit character such as `;`.

Let me know if that doesn't resolve the problem you're having.

**Comment by audreychenjj-2019** [comment]
It worked! Thank you!
