### ISSUE TITLE
No info.php in server document root directory

### ISSUE THREAD

**Issue by conbainbridge** [susanBuck/e28-fall19#55]
When looking at the contents of /var/www/html, I only see the index.html (no info.php). Is this ok?

**Comment by susanBuck** [comment]
Yup, that's okay. `info.php` used to be included by default on new servers - it was a file that output information about the server. Looks like it's no longer included so I'll update the notes. Sorry for the confusion!

**Comment by extra808** [comment]
`info.php` only contains the `phpinfo();` command. It can be handy when setting up a server but having the results of that command at a commonly used file path can be bad for security; malicious people can use the information to more easily attack your server.
