### ISSUE TITLE
PSA: Connecting Digital Ocean SSH key to GitHub ("The authenticity of host 'github.com (IP ADDRESS)' can't be established.")

### ISSUE THREAD

**Issue by terichadbourne** [susanBuck/e28-fall19#56]
I received a warning message when testing the SSH connection from my Digital Ocean server to my GitHub account. 

The `ssh -T git@github.com` command led to this response: 

```
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)?
```

I found a [helpful article on GitHub's site](https://help.github.com/en/articles/testing-your-ssh-connection) that convinced me it was okay to say yes, because the RSA key fingerprint listed in my console was one of the two specific ones mentioned as safe in their documentation. 

After saying yes, I got the correct "warning" message I'd originally anticipated, as was shown in Susan's video: 
```
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
Hi terichadbourne! You've successfully authenticated, but GitHub does not provide shell access.
```
Hope this is helpful to someone else!

**Comment by susanBuck** [comment]
Great info, Teri, thanks for sharing.

**Comment by kreinholz** [comment]
Thanks, @terichadbourne! I'd come across this in another class (CSCI E-31, which I'd highly recommend), and per the instructions, just said "yes" and "accepted the risk." That said, security errors are always a scary thing to come across, and reassurances like this are, well, reassuring!
