### ISSUE TITLE
Text input with a combination of number and string

### ISSUE THREAD

**Issue by audreychenjj-2019** [susanBuck/e28-fall19#58]
I used the code 

```HTML
<input type='text' id='answer' v-model.number.lazy='answer' v-on:keyup.enter='submitAnswer'>
```

When I enter 25 or 25abcdef, the result is the same. It seems that the code doesn't recognize strings following the number. Any suggestion how I can fix this?

![number string](https://user-images.githubusercontent.com/54291820/66301002-23d93580-e8ab-11e9-8177-39e7864a3887.PNG)

**Comment by coinshot** [comment]
Change the type from text to number.

`<input type='number' ...`

**Comment by susanBuck** [comment]
+1 to @coinshot's suggestion. 👍
