### ISSUE TITLE
Question on Project 1 Implementation

### ISSUE THREAD

**Issue by gaderrick** [susanBuck/e28-fall19#59]
I'm posting this here versus sending an email to Susan (since it might be on other's minds)-

With regards to the "computer's" moves:

1) Should the computer's "moves" be automatic, or
2) Can the I prompt the user to make the computer's move, or
3) Does it matter? :)

**Comment by susanBuck** [comment]
Choice is yours. : )

Typically, I'd expect the computer move to be automatic - via either a random choice or some pre-programmed logic. 

But I'm open to games where the player also chooses the computer's move if it fits some idea you have in mind.

**Comment by gaderrick** [comment]
I should have provided a little more context :). I have it setup to where the player has to hit a "Click for Computer Turn" button that starts the computer's turn. Otherwise certain status updates are only on the screen for a split second.

Thanks!

**Comment by susanBuck** [comment]
Ahh, I see! So the player is not choosing their move, they're just initiating it. Got it.

That's also fine. 👍
