### ISSUE TITLE
Semicolon usage 

### ISSUE THREAD

**Issue by terichadbourne** [susanBuck/e28-fall19#60]
@susanBuck I remember you stating in one of the videos that you choose to use the semicolons that aren’t actually needed in JavaScript, and I know in addition to meeting specific project requirements we need to follow generally accepted JS standards. I was trained out of the usage of those semicolons a while back and don’t use them in my codebase at work. Just wanted to confirm we won’t get points knocked off for skipping the unnecessary ones?

**Comment by susanBuck** [comment]
You won't get any points knocked off. 

It's a personal/team preference thing, so the most important thing is just that you're consistent with your preference.

For anyone reading this and trying to decide whether you want to go the "always semi-colon" vs. "sometimes semi-colon" path, here's a thorough read on the subject:

http://www.bradoncode.com/blog/2015/08/26/javascript-semi-colon-insertion/

There's also a ton of discussion on the topic on Stackoverflow - It can be useful to read through the pros/cons/opinions there and decide which approach works best for you.

**Comment by terichadbourne** [comment]
Thanks for confirming @susanbuck!
