### ISSUE TITLE
How to keep the "correct" answer for multiple attempts from a player?

### ISSUE THREAD

**Issue by audreychenjj-2019** [susanBuck/e28-fall19#61]
I asked this question when we were building the first game using Javascript + HTML before learning Vue.js framework. I am trying to figure out a way to keep the same "correct" answer which was generated by random() function. Every time when a player submits a guess, the "correct" answer changes then the feedback is not useful. Any suggestion on the approach?

**Comment by susanBuck** [comment]
Hi @audreychenjj-2019 -

Is the code you have to generate the correct answer part of your submit function? If so, I'd move it out of so it's not being regenerated every time your user submits a guess.

As an example of this, we can look at the [Word Scramble game](https://github.com/susanBuck/e28/tree/master/p1) I showed in the last lecture...

Note how my **submitGuess** function only checks the guess - it does not regenerate a correct answer.

```js
submitGuess: function () {
            this.correct = this.guess == this.word;
            this.feedback = true;
        },
```

It's only my **loadGame** function that regenerates the answer, and that's only invoked (1) when the game first starts and (2) when the user clicks "Play again" after winning.

```js
loadGame: function () {
            this.feedback = false;
            this.guess = '';

            while (this.word === this.lastWord) {
                this.choice = this.words[Math.floor(Math.random() * this.words.length)];
                this.word = this.choice[0];
                this.hint = this.choice[1];
            }

            this.lastWord = this.word;
        }
```

If that example doesn't clarify things, let me know!

For anyone else following this thread - this is the previous thread @audreychenjj-2019 is referencing:
https://github.com/susanBuck/e28-fall19/issues/19

**Comment by audreychenjj-2019** [comment]
Yes, this example is clear. I was able to solve my problem by following the steps in the example. Thanks!
