### ISSUE TITLE
Is there a way to add another SSH key to a Droplet?

### ISSUE THREAD

**Issue by rokmesojedec** [susanBuck/e28-fall19#65]
Hi all, 

does anyone know if there's a way to add an additional SSH key to the LAMP server used by our droplets? I'm working from multiple machines so it would be practical if I could use multiple SSH keys.

**Comment by naztronaut** [comment]
From [Susan's Reply Here](https://github.com/susanBuck/e28-fall19/issues/43#issuecomment-535993471):

1. Generate a new key pair on your laptop.
2. Get a copy of the generated public key from your laptop to your desktop.
3. SSH into your DO server from your desktop and add your laptops public key to this file: ~/.ssh/authorized_keys

Longer answer: https://www.digitalocean.com/docs/droplets/how-to/add-ssh-keys/to-existing-droplet/

**Comment by rokmesojedec** [comment]
Thank you!
