### ISSUE TITLE
two functions @click ?

### ISSUE THREAD

**Issue by mourad1974** [susanBuck/e28-fall19#68]
Hi,
could anyone help to figure out if this is possible?
can I call two functions at a single @click

Thank you

**Comment by susanBuck** [comment]
Good suggestions in the post @terichadbourne shared.

The answers that suggest the following are the cleanest IMO:
```js
<button @click='myFunc1(); myFunc2()'>Go</button>
```

**Comment by ihimawan** [comment]
Is it the cleanest solution though? I feel like you should just have one function that executes myFunc1() and myFunc2() one after another. In the case of `@click='myFunc1(); myFunc2()'`, would the two functions run at the same time?

**Comment by mourad1974** [comment]
Perfect, Thank you all

**Comment by extra808** [comment]
@ihimawan 
> I feel like you should just have one function

I agree, even if Vue's click handler will accept multiple functions in one attribute, it doesn't strike me as a good way to organize one's code.

**Comment by susanBuck** [comment]
I meant the cleanest in terms of literally invoking two separate functions directly from the listener. In contrast to some of the other options offered in that thread such as: 

```html
<div v-on:click="return function() { fn1('foo');fn2('bar'); }()"> </div> 
```

Agreed a bigger picture rethinking of how/why two functions are invoked directly from the listener is worth considering.

**Comment by mourad1974** [comment]
thanks you,
honestly the first suggestion worked perfect for me, i don't know if I can implement this way
