### ISSUE TITLE
Adjusting the classes of all elements of a certain class in Vue

### ISSUE THREAD

**Issue by terichadbourne** [susanBuck/e28-fall19#69]
In my "guess the word" app ([current draft of code here](https://github.com/terichadbourne/e28/tree/master/p1)) I'm using `v-for` to to loop through the alphabet and print a button for each guessable letter. I have a function that's called when each button is clicked and passes the value of that letter, and inside that function I can use event.target to disable the button and add a class that I used to change its color based on whether the guess was correct. This all works great within the context of a single game.

```html
      <button v-for="letter in alphabet" class="guess" @click="guess(letter), $event">
        {{letter}}
      </button>
```
 
```javascript
        guess: function (guessedLetter) {
          event.target.disabled = true
          if (this.isCorrect(guessedLetter)) {
            event.target.classList.add('correct')
            this.correctGuesses.push(guessedLetter)
          } else {
            event.target.classList.add('incorrect')
           // etc...
          }
        }
```

The trouble comes when I start a new game and want to clear both the `disabled` state and my special classes from all of those buttons. I came up with a solution based on vanilla JS that finds all of these buttons and updates them directly in the DOM, but that feels to me like a hacky workaround that I shouldn't need to use in Vue. 

```javascript
let guessButtons = document.getElementsByClassName('guess')
          Array.prototype.forEach.call(guessButtons, function(button) {
              button.disabled = false
              button.classList.remove('correct', 'incorrect')
          })
```
I use Vue at work (without having actually studied it yet ) and I don't think I've ever had to use `document.getElementsByClassName` or `document.getElementById`, but I'm not sure how else I could reference a swath of elements once I can no longer use `event.target` on them. I'm pretty sure I'd be able to do this using [the object syntax for class bindings](https://v1.vuejs.org/guide/class-and-style.html#Object-Syntax) if we were using Vue components, where each button could have its own data properties, so I'm not sure if it's the lack of components that's a blocker here or if I'm missing a more obvious Vue-like solution. This clearly isn't urgent since I found a technique that's working, just curious if there's a better way to accomplish it.

**Comment by ihimawan** [comment]
I think that ideally you shouldn't ever need to use anything that modifies the DOM while you are using Vue, because it defeats the purpose of Vue. 

Check this out, might help you: https://vuejs.org/v2/guide/class-and-style.html

**Comment by coinshot** [comment]
To make it less imperative, this would be a way to go:

1. Get rid of all the DOM modifiers in your code and do all the disabling and "class handling" stuff in a computed property, this gives you an object for each word that defines if it is correct or not, if it is clicked or not and what the word is just with a simple reduce:

```
...
newAlphabet() {
      return this.alphabet.reduce((newA, w) => [...newA,{word: w,class: this.isCorrect(w) ? "correct" : "incorrect",clicked: false}],[]);
},
...
```

2. In your HTML use this new computed property instead, like this:
```
...
<button v-for="letter in newAlphabet" class="guess"  :class="{[letter.class] : letter.clicked}" :disabled="letter.clicked" @click="guess(letter.word)">
        {{letter.word}}
</button>
...
```

3. Now all you need to do is to handle the click "guess()" in your script, like this:

```
...
guess: function(guessedLetter) {
      ... 
      this.newAlphabet.map(e => (e.clicked = e.word == guessedLetter ? true : e.clicked));
      ... 
    }
...

```

---

So here is what happens in a nutshell, your new property will update based on the new word, and you do not need to do it manually, which makes your code much less declarative.

**Comment by terichadbourne** [comment]
Thanks for the suggestion @coinshot. I did consider turning my alphabet into a bunch of objects with more info, but I had decided to skip that complexity when it seemed like I had a reasonable way to add the button classes about whether a letter was right or wrong on click. I see how your code addresses my same concern about making sure sneaky developers (at least those without the Vue add-on) can't turn on their inspector and cheat by peeking at classes before they make a selection. :) 

Still curious whether there's a simpler way to reference a bunch of elements in Vue without components and without being a context where `event.target` is available. ¯\_(ツ)_/¯

**Comment by coinshot** [comment]
Sure, but the class does not show before it is clicked, you cannot tell anything by looking up the HTML.

**Comment by andmade** [comment]
Instead of making a button for each letter, you could treat the letters as radio options with a v-model of guessedLetter. That way you would only have to change one button of the game reset. Then in your function to check guess, you can reset the value of guessedLetter (to clear the radio buttons) and remove the value from the alphabet, in which case the letter would be removed from the possible options (you can have a separate div where you display guessed letters if you want). Then, when you reset the game, reset the alphabet to your initial value, and all the letters will appear again.

Something like...

```Vue
<template v-for="letter in alphabet">
  <label :for="letter">{{ letter }}</label>
  <input type="radio" :id="letter" :value="letter" v-model="guessedLetter" />
</template>
<button @click="checkGuess()" @keyup.enter="checkGuess()">
  Submit Guess
</button>
```
Then in `checkGuess()`, something like:

```Vue
    checkGuess: function() {
      //some other game code that evals based on this.isCorrect//
      this.alphabet.splice(this.alphabet.indexOf(this.guessedLetter), 1);
      this.currentGuesses.push(this.guessedLetter);
      this.guessedLetter = null;
    },
```
But if you want to keep it your way, you could do something like:

```Vue
        <button
          v-for="letter in alphabet"
          class="guess"
          @click="guess(letter)"
          :disabled="currentGuesses.includes(letter)"
        >
          {{ letter }}
        </button>
```

When you wipe out currentGuesses on the reset, the buttons should re-enable.

**Comment by terichadbourne** [comment]
Thanks for the suggestion. I like using buttons because it leaves a very simple and colorful record of what's already been guessed, but by combining some of the suggestions from @coinshot and @andmade I was able to avoid all of my direct DOM manipulation. 
```html
        <button
          v-for="letter in alphabet"
          @click="guess(letter), $event"
          :disabled="!liveGame || (correctGuesses.includes(letter) || incorrectGuesses.includes(letter))"
          class="guess"
          :class="[{incorrect: incorrectGuesses.includes(letter)}, {correct: correctGuesses.includes(letter)}]">
          {{letter}}
        </button>
```
```javascript
        guess: function (guessedLetter) {
          if (this.isCorrect(guessedLetter)) {
            this.correctGuesses.push(guessedLetter)
          } else {
            this.incorrectGuesses.push(guessedLetter)
            // do some other stuff 
            }
          }
        }
```
This hinged on capturing my `incorrectGuesses` in a new array alongside my `correctGuesses`, but I didn't have to turn my initial alphabet into a more complex object. And as a bonus, I can now have a computed property for `strikes` that returns the length of my `incorrectGuesses` array instead of adjusting a data property manually.

Making progress! 

![image](https://user-images.githubusercontent.com/19171465/66610407-70fa2780-eb89-11e9-9d80-d1b2c7c658df.png)
