### ISSUE TITLE
git clone issue

### ISSUE THREAD

**Issue by claudiomanuelboston** [susanBuck/e28-fall19#7]
I am getting the following error when trying to clone the repo

$ git clone git@github.com:claudiomanuelboston/e28.git
Cloning into 'e28'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by susanBuck** [comment]
`Permission denied (publickey).` is the same error you noted in issue #6. Until you resolve that issue, you'll continue to get this error whenever you attempt to connect to github.

I'm going to go ahead and close this issue so we can consolidate the troubleshooting in #6.
