### ISSUE TITLE
Inconsistent behavior in Vue from nested in event handler function vs other function

### ISSUE THREAD

**Issue by cgloge** [susanBuck/e28-fall19#70]
Hi there,

I'm running into an issue for Vue and would love to get folks advice on what might be going wrong here.

I'm able to successfully clear an interval in an event. 

**This works fine:**
```
scoreClick: function (e) {
    clearInterval(timer);
 },
```

**This does not work:**
```
gameOver: function () {
    clearInterval(timer);
 },

scoreClick: function (e) {
    this.gameOver();
 },
```
Any ideas on why this is happening?

Thanks in advance!

**Comment by ihimawan** [comment]
Where is `timer` defined? Is it inside Vue?

**Comment by coinshot** [comment]
It could be a scope issue, make timer global.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by audreychenjj-2019** [comment]
I tend to agree with what the previous comments said about the scope of timer. 

Question for you though, why do you want to nest your functions that way? Not knowing what you're trying to accomplish I feel that for the little game we're developing there's no advantage of nesting functions for more than 2 layers.

**Comment by phildarnowsky** [comment]
It might also be worth throwing in `console.log(this)` in each function just to make sure it is what you think it is.

**Comment by conc2304** [comment]
if timer is defined in the Vue instance and you are trying to access Timer from a component you may have to pass in timer as a property perhaps

**Comment by susanBuck** [comment]
I believe this question was relevant to project 2 which has been submitted, so I'm going to assume @cgloge got their answer and close this thread out.

Feel free to open a new thread or continue the discussion if questions are still pending though.
