### ISSUE TITLE
alternate favicon solution

### ISSUE THREAD

**Issue by extra808** [susanBuck/e28-fall19#71]
Warning about no favicon.ico in the console seems to only be a Chrome hang-up, Firefox and Safari don't do that. However, it is common for browsers to request favicons from the server automatically. Last week, I learned what may be the smallest possible favicon, 27 bytes; instead of a tiny blank file on your server, put this in the `<head>` of every web page:
```HTML
<link href=data:, rel=icon>
```
## Cons:
- a little more code you have to remember to include in every page, vs. dropping a file in the root of a site
- would be more data transferred than a single 198 byte favicon.ico file for site designs that involve using 8+ pages
## Pros:
- less data for sites with fewer pages (like SPAs)
- one less web request the browser has to make
- no web server log entry

**Comment by susanBuck** [comment]
Good tip! I should note the transparent solution I showed was only intended for local/temporary sites. 

On real sites, I always recommend devoting the time to constructing a real favicon that represents your brand/theme.

**Comment by extra808** [comment]
To be thorough you can use a tool like https://realfavicongenerator.net to produce not just a favicon.ico but seven other variants and seven lines of HTML to go with them, from 16x16 to 512x512 plus an SVG.

**Comment by pausman** [comment]
the site https://favicon.io/ also works well.
