### ISSUE TITLE
JSX as a Vue component template

### ISSUE THREAD

**Issue by kreinholz** [susanBuck/e28-fall19#74]
The reading [here](https://vuejsdevelopers.com/2017/03/24/vue-js-component-templates/) noted that it is possible to use JSX as a template option within Vue! I found this fascinating after dabbling a little with React, which relies heavily on JSX!

I was just wondering if anyone had experience using JSX templates within Vue, and moreover whether it was possible/advisable to use JSX in conjunction with Single File Components (a topic I've very interested in exploring, as putting all components in the same file, which would grow incredibly long and almost impossible to maintain in a complex web app, seemed like a big downside to Vue compared to either Angular or React...Single File Components seem to be a way of organizing code in Vue similarly to React or Angular, and a key to making code maintainable and reusable by either myself or other developers).

As I wait impatiently to dive into Single File Components, the note about Vue accepting JSX templates just caught my eye, as it seems like a potential way to bridge development for Vue and development for React, for those moving back and forth between frameworks. I wonder, though, whether JSX has much traction within the Vue community? The article noted that it is "controversial." (Frankly I think Angular's use of TypeScript could be considered equally "controversial," since it likewise requires transpiling).

So far, I like Vue. It seems way more digestible than the Angular behemoth, and easier to read/pick up than React (due in large part to JSX). I wonder about managing state across multiple Single File Components, and whether a system similar to Redux will come into play, but I'll be patient and wait until we dive into SFCs. Good stuff this week!

**Comment by susanBuck** [comment]
I've always seen JSX in Vue as something that satisfies those coming from/used to React patterns, which is pretty in line with your perception about it being a good bridge between the frameworks.

That being said, I'd say SFCs are more ubiquitously used. It's a preference thing.

re: Managing state - You are correct in thinking a system similar to Redux will come into play - it's called Vuex - https://vuex.vuejs.org.

Vue tries to keep the core framework slim, but gives you the option to scale up with supported libraries like Vuex for state management and [Vue router](https://router.vuejs.org/) for routing/SPAs.

**Comment by kreinholz** [comment]
I couldn't help myself and started reading the documentation on SFCs...now I'm going to take a peek at Vuex! Thank you for the preview! This is the meaty stuff I'm looking forward to diving into!

The scalability of Vue strikes me as one of its most appealing features. Angular forces an imposing structure on the developer...it's a great system, but there's a steep learning curve and I found it a tad overwhelming, plus there's not much choice about how to do things...there's the "correct" Angular way to do it, and then there are ugly hacks. React seems more flexible, but again the JSX is a bit of a turnoff. Vue seems to strike a very nice balance between being accessible and being scalable. Should be a fun next few weeks!

**Comment by ihimawan** [comment]
I think in all of the UI frameworks I've learned (Angular, React, Vue), using JSX has been the most intuitive way for me to use. I didn't know that Vue could use JSX! I'd definitely read into this more.

You mentioned Angular, I sort of "quit" Angular when they came up with Angular 2, which I felt were almost completely different that what I learned in AngularJS.. and it wasn't intuitive for me anymore. Admittedly though, this was way back 3 years ago and I didn't have very good understanding into UI/Javascript concepts. But still it was an annoying switch :)

Personally right now I very much enjoy ReactJS the most. I enjoy the usage of the class (and extends) syntax and arrow functions. And of course the JSX is awesome.

**Comment by kreinholz** [comment]
@ihimawan I’ve heard of others leaving the Angular fold after the drastic move from AngularJS to Angular 2 (and now the subsequent versions which follow the Angular 2 codebase). I think it’s good to know, since it’s so prolific, and the same definitely goes for React (which I agree is more fun to work with than Angular).
