### ISSUE TITLE
Hiring Web-Developers in Boston

### ISSUE THREAD

**Issue by conc2304** [susanBuck/e28-fall19#80]
Hey guys, 
I work at SimpliSafe in downtown Boston and as an effort to ramp up our engineering efforts we have begun looking for both front-end and back-end web developers to join our team.  There are currently opportunities in all levels of these stacks.  If you are interested in the positions and/or have questions about the work that we do at SimpliSafe please feel free to email me at jose.c@simplisafe.com with your resume and I can forward it to our hiring manager. 

Thanks again Susan for letting me post this here!

**Comment by mourad1974** [comment]
Thank you or sharing this, I wish I could have that skill now, still working on it...
Very nice very from you.  Thanks again :)

**Comment by audreychenjj-2019** [comment]
If a job post requires Angular I think someone who is very familiar with Vue.js should be able to apply as well, everything else equal. Is that a fair assumption?

**Comment by conc2304** [comment]
@audreychenjj-2019 I would say that syntax-wise they are almost identical, so jump from one to the other should be relatively pain free in my opinion.  There are some structural difference in where code lives and interacts with each other, but nothing dauntingly different.  Here is a quick comparison between the two frameworks https://buttercms.com/blog/comparing-angular-vs-vue.

**Comment by apatruno618** [comment]
> Thank you or sharing this, I wish I could have that skill now, still working on it...
> Very nice very from you. Thanks again :)

Agreed

**Comment by phildarnowsky** [comment]
@susanBuck Is it fair game for anyone to post job reqs, because my work is looking for engineers as well.

**Comment by susanBuck** [comment]
@phildarnowsky - Yup, go for it.
