### ISSUE TITLE
PSA: Updating Xcode Command-line Tools for MacOS Catalina

### ISSUE THREAD

**Issue by spttruong** [susanBuck/e28-fall19#83]
Those updating to MacOS Catalina will need to update Command line tools to get Git to function properly again. 

I updated yesterday so today I was running into an issue where `$ git status ` would give me this error:
```error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun```

I would also get a warning in VS Code. 
![image](https://user-images.githubusercontent.com/49035567/67535101-23a8aa80-f69f-11e9-80be-3927a35e86ed.png)

To remedy this, type the following into your terminal:
`$ xcode-select --install`

Continue to follow the prompts until everything is installed. Once finished, restart the terminal.

[Solution from stackoverflow](https://stackoverflow.com/questions/52522565/git-is-not-working-after-macos-update-xcrun-error-invalid-active-developer-pa).

**Comment by susanBuck** [comment]
I just had a student ask about this in my other class. You saved me from having to search for the fix. : )

Thanks for sharing!
