### ISSUE TITLE
Something is wrong with the XAMPP installation :-(

### ISSUE THREAD

**Issue by mourad1974** [susanBuck/e28-fall19#9]
HI,
I would appreciate if someone could help me with this:
after installing XAMPP  the server turned on (green)
![server](https://user-images.githubusercontent.com/35425870/64528979-c798eb00-d2d7-11e9-99a2-4c2d1bcbd789.png)

 When I type "htdocs" or "/Applications/XAMPP/xamppfiles/htdocs" it doesn't take me to the index.php file. when i check the index.php it shows this 
![message](https://user-images.githubusercontent.com/35425870/64528770-4d686680-d2d7-11e9-89da-4895c7cfba57.png)

 instead it shows me the main page
![Screen Shot 2019-09-08 at 10 23 02 PM](https://user-images.githubusercontent.com/35425870/64530691-c5d12680-d2db-11e9-92f3-fd0b511b7f84.png)

i tried to reinstal the app so many time with so many version of it but nothing seems to help

on the web, many people have the same issue  but I didn't see any solution to that.
Thank you

**Comment by extra808** [comment]
You didn't indicate where you were typing those things but in the web browser address bar, you don't type any of that, just enter `localhost`.

**Comment by mourad1974** [comment]
> You didn't indicate where you were typing those things but in the web browser address bar, you don't type any of that, just enter `localhost`.

sorry  i wanted to say I type localhost on the web browser, but nothing happens

**Comment by ibrodsk76** [comment]
What you are seeing is correct. It opens a "dashboard" page, just like your index.php tells it to do.
 Just continue following the instructions: delete index.php file and replace it with your own. Then you'll see the output you expect to see.

**Comment by mourad1974** [comment]
That solved the problem, thank you  @extra808, @ibrodsk76 and @rokmesojedec for you help
