### ISSUE TITLE
Vuex

### ISSUE THREAD

**Issue by coinshot** [susanBuck/e28-fall19#90]
From the course schedule, It appears we are not going into Vuex within this course. Wrt the project guidelines, is it fine if I use Vuex in my next projects while they get larger?

**Comment by kreinholz** [comment]
+1 for @coinshot's question. I'm working on project2 and thinking I'll need to use some combination of **props** and **events** to pass data around...for this small-scale project that seems like it should be sufficient, but **Vuex** would be a nice topic to cover it time permits, as I can't see feasibly building a larger web app without a more organized approach to state management.

**Comment by susanBuck** [comment]
@coinshot - Yup, you can use Vuex in P3 and/or P4 if you'd like.

@kreinholz - We will cover Vuex and state management - it's not on the schedule though (so you're not missing anything : ) It was going to be the topic I covered in the TBD lecture I had on the schedule before I rearranged things in Week 7. Now I'm just trying to decide which week(s) it would best marge in with the other topics. It might get spread out over a couple weeks, but we'll get there. 👍
