### ISSUE TITLE
Issues with iterating over elements in Project 2 template

### ISSUE THREAD

**Issue by cgloge** [susanBuck/e28-fall19#91]
Hey there,

In my previous project, I build a table by looping through a 2-dimensional array. Something like this...
```
 <td v-for="col in columns">
    {{row[col]}}
 </td>
```
When I tried to import this into my new Project 2 template, I got the following error:
**Elements in iteration expect to have 'v-bind:key' directives.**

After searching on StackOverflow, many folks suggested a format like the following:
```
<td v-for="col in columns" :key="col">
    {{row[col]}}
 </td>

```
This works but is causing a new warning: 
**Avoid using non-primitive value as key, use string/number value instead.**

I'm not sure how to resolve this. I've tried to look through other proposed solutions online, but have had no luck. 

Any advice?

**Comment by coinshot** [comment]
Use the index: 
`v-for="(col, i) in columns" :key=“i”>’

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cgloge** [comment]
That did the trick! I didn't realize that you could use the key or index. 

Thank you!
