### ISSUE TITLE
Quiz questions from API - quality of JSON data

### ISSUE THREAD

**Issue by audreychenjj-2019** [susanBuck/e28-fall19#93]
If I use some open API for pulling some random questions into my quiz in project 2, will the quality of the questions be evaluated? For example, I notice that there are some small issues with the objects in the Json file such as "71% of the Earth&#039;s surface is made up of" instead of "71% of the Earth's surface is made up of". 

Because these questions and answers are provided by other users I manually cannot verify them before using them.

Is this ok? Or I should write up my own list of questions in a simple array to guarantee the quality of the questions and answers?

**Comment by susanBuck** [comment]
Yup, that's okay. Just make a brief note about it in your README.md file.

**Comment by audreychenjj-2019** [comment]
I am still curious to solve this quotation problem in how I fetch JSON content though. The example I gave above doesn't look like that all at in my quiz. 
Here's a screenshot of the JSON content:

![p2 JSON string problem](https://user-images.githubusercontent.com/54291820/67792468-6ddeb280-fa36-11e9-9cf9-d152c4b12084.PNG)

**Comment by audreychenjj-2019** [comment]
I got a work-round for this and sorta fixed the issue. Thanks for your help!
