### ISSUE TITLE
Getting error when running "npm run dev" on Mac (integrated build)

### ISSUE THREAD

**Issue by gaderrick** [susanBuck/e28-fall19#96]
Hello- 

I started working on P2 and I'm running into an error that has me baffled. One caveat, I normally use a PC, but on travel I'm using a Mac so I may have missed something "significant" in setting everything up. That said, the week 8 sample project works fine, and I based my skeleton frame on the instructions from the class notes on "Integrated builds."

In the index.html file I have this:
`<script src='/js/script.js' defer></script>`

and in the file 'src/script.js' I have this:
```javascript
import Vue from 'vue';
// root Vue instance
let app = new Vue({
    el: '#app',
    components: {
    },
    data: {
        showRules: true,
        'maxAllowedGuesses': 10,        // max number of guesses allowed for each game
        'maxRandomNumber': 100         // The max number the random number could be
    },
    methods: {
        toggleRules: function () {
        },
    }
});
```
My current directory for P2 looks like this:
p2
--js
----script.js
--node_modules
--src
----script.js
.gitignore
index.html
mix-manifest.json
package-lock.json
package.json
webpack.mix.js

When I run "npm run dev", however, I get the following error in the console:
```
Uncaught ReferenceError: Vue is not defined
    at Object../src/script.js (script.js:99)
    at __webpack_require__ (script.js:20)
    at Object.0 (script.js:115)
    at __webpack_require__ (script.js:20)
    at script.js:84
    at script.js:87
```

Interestingly if I add the Vue package through the CDN <script> link it works. Any assistance would be appreciated. I'm almost at the point of nuking the folder at starting it over.

Thanks,
Jerry

**Comment by pausman** [comment]
Did you run npm install to install the modules in your package.json?
Vue should in your node_modules folder.

**Comment by gaderrick** [comment]
Yes, I ran "npm install" and I see the following Vue related entries:
-vue
-vue-hot-reload-api
-vue-loader
-vue-style-loader
-vue-template-compiler
-vue-template-es2015-compiler

**Comment by gaderrick** [comment]
Update- I should not be allowed to use Mac computers (although they're really cool). I had too many versions of different projects open trying to debug the code and missed the fact that the script.js file for P2 had unsaved changes. Sorry for the trouble. :(
