### ISSUE TITLE
How to debug after building with "npm run dev" ?

### ISSUE THREAD

**Issue by daveyshindig** [susanBuck/e28-fall19#97]
Hi all,

I think I've gotten my build working, using all the tooling to which we've been introduced over the last week, but I have run into a stumbling block: unless I'm mistaken, when we build with `npm run dev`, the process sticks all the JS into a single file of unmanageable proportions and makes it practically impossible to use my browser's debugging tools. 

Is there some preferable way to build during development? Are we supposed to use code mapping or something like that? Or am I missing something completely?

Thanks in advance for any pointers. 😸

**Comment by coinshot** [comment]
Assuming you are using the integrated build, you should run `npm run prod` to build.

**Comment by coinshot** [comment]
You can try the [Chrome debugger extension](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome) for VScode and put your breakpoints in VSCode. I use this all the time, works really well.

**Comment by extra808** [comment]
I didn't find any documentation of it on laravel-mix.com but I found on [laravel.com](https://laravel.com/docs/6.x/mix#css-source-maps) you can tell Mix to produce source maps

```JavaScript
mix.js('src/script.js', 'js')
	.sourceMaps(false, 'source-map');
```

[Webpack Devtool](https://webpack.js.org/configuration/devtool/) lists parameters other than `source-map` to control what's output.

**Comment by ihimawan** [comment]
I usually `console.log()` things. Saves time especially if you already kind of know where the problem lies.

**Comment by susanBuck** [comment]
@daveyshindig - Can you clarify which specific browser debug features you're trying to use?

For example, are you referring to using breakpoints?

Or are you referring to finding the specific line/file where an error is occuring?

If the latter, @extra808's note of adding `.sourceMaps(false, 'source-map')` in your Laravel Mix config file (`webpack.mix.js`) is what you're looking for.

Without it, when an error occurs it gives you reference to the error in the bundled JS file (line 12848):

![image](https://user-images.githubusercontent.com/237711/67820694-b1fea100-fa90-11e9-8ce6-0a8259ba2bc0.png)

With it, it shows gives you reference to the error in the source file (line 19):

![image](https://user-images.githubusercontent.com/237711/67820727-cf336f80-fa90-11e9-83fa-c5173bcef425.png)

(In this example, it happens to be the case that my bundled file and source file share the same name (`script.js`))

**Comment by daveyshindig** [comment]
I was trying to use breakpoints (for exploratory purposes, not necessarily to resolve any error in particular).

**Comment by susanBuck** [comment]
Had a chance to take a closer look at this today (sorry for the delay!).

Once source mapping is enabled, you should be able to get to the source files as shown in this screenshot:

![image](https://user-images.githubusercontent.com/237711/68146138-56576c00-ff05-11e9-96b5-ef62dc1351ce.png)

From there I was able to set/test breakpoints.

**Comment by daveyshindig** [comment]
thank you to all who commented! :)
