### ISSUE TITLE
Still trying to understand Single File Components

### ISSUE THREAD

**Issue by bibliodrone** [susanBuck/e28-fall19#98]
For project 2, how do I determine what code should be refactored into the App.vue file and what should be refactored into the component .vue file(s)? I have been studying Week8spa and trying to generalize the approach used there to my own project, which is more complex. I don't quite see the overall logic behind how I get from what I had in the previous project to the single file structure used here. Do I need separate components at all? I know that question has been asked, previously. 

In **RoundDetail.vue**, in the <script> section, the statement ``template: "#round-detail"`` is identified with the ``<round-detail>`` section in **App.vue**, and is setting the types and names of variables, but why do it that way? I trying to visualize what is really going on here so that I understand the logic behind what I am supposed to be doing.

Gerry

**Comment by gaderrick** [comment]
Gerry-

I started off with a grand plan to "componentize" everything possible, but what I found is that it is definitely easier to focus on the "repeatable" output type functionality (think for-next looping over arrays). With regards to your question about setting the types and names of variables, what helped me figure this out was to think of the component as a function or procedure and the names/types were defining the variables that the component had access to (shared from the parent app). This also helped (Passing Data to Child Components with Props): (https://vuejs.org/v2/guide/components.html).

Hope this helped

Jerry

**Comment by audreychenjj-2019** [comment]
I'm struggling a little bit in determining what needs to be a child component and what can be included into the parent component as well.

**Comment by susanBuck** [comment]
@audreychenjj-2019 

Looking at your P1, I see 3 blocks of repeated code ([index.html Line 61](https://github.com/audreychenjj-2019/e28/blob/master/p1/index.html#L68)):

```html
 <div v-if='level == "easy"'>Guess a whole number between 1 and 10.
                <input type='number' id='guess' v-model.number='guess' v-on:keyup.enter='submitGuess'>
                <button v-on:click='submitGuess' v-on:keyup.enter='submitGuess'>Submit guess</button>
            </div>
            <div v-if='level == "moderate"'>Guess a whole number between 1 and 25.
                <input type='number' id='guess' v-model.number='guess' v-on:keyup.enter='submitGuess'>
                <button v-on:click='submitGuess' v-on:keyup.enter='submitGuess'>Submit guess</button>
            </div>
            <div v-if='level == "difficult"'>Guess a whole number between 1 and 50.
                <input type='number' id='guess' v-model.number='guess' v-on:keyup.enter='submitGuess'>
                <button v-on:click='submitGuess' v-on:keyup.enter='submitGuess'>Submit guess</button>
            </div>
```


Here we have 3 divs that are exactly the same except a small part of the language that varies between `1 and 10`, `1 and 25`, and `1 and 50`.

There are ways to optimize this without components ([examples here](https://gist.github.com/susanBuck/faf9341f826421540424add34beaf306)), but you could also turn it into a component where it's passed the level as a prop.

Beyond that, there are several aspects of your game that could be turned in components, such that maybe your final root template looks like this:

```html
<game-start v-if='gameMode == "start"'></game-play>

<game-play v-if='gameMode == "play"'>
     <game-prompt :level='level'>
</game-play>

<game-guesses></game-guesses>

<game-feedback v-if='feedback'></game-feedback>

<button v-if='submitted' v-on:click='loadGame'>Reload the game.</button>
```

Do all of these things *need* to be components? Not necessarily - as they're not repeated. But there's no reason they *can't* be components, and it serves the purpose of practicing with components. (Even if you just turned one of them into a component, it would meet the project requirements)

Other options: 
+ Add some additional aspect to your game that could take advantage of components. 
+ Build a different game with some repeatable aspect that would take advantage of components.

**Comment by bibliodrone** [comment]
Thank you all for the helpful replies.  Sometimes when learning a new set of concepts like these it can help to step back from all the details about syntax, etc. and make sure I have an overall understanding of what is happening. The conceptual analogy between SFC's and functions is helpful in terms of grokking the overall concept and when considering where to focus in this particular assignment.

-Gerry

**Comment by audreychenjj-2019** [comment]
I really like the example using my own p1 to show how components can be used. I'm building a completely different game this time. Will try my best to use one or two components. Thanks!

**Comment by bibliodrone** [comment]
Hi, 

I am still not quite sure what I am doing. I understand the overall idea, I think, but I am not clear enough on where to put methods and watches so that they function properly.  The Vue console error messages are relatively helpful, at least.

One specific error message I have been having relates what to an array called 'items' that I was using as a source of randomly chosen characters. It is currently in the 'props' declaration. It seems that most props can have a 'default' value that corresponds to their 'type', but in this case that is not working:

```
error: Type of the default value for 'items' prop must be a function (vue/require-valid-default-prop) at src\App.vue:34:7:
  32 |     items: {
  33 |       type: Array,
> 34 |       default: ["�", "➆", "♠", "�", "♥", "�"]
     |       ^
  35 |     }
  36 |   },
  37 |
```

Thanks, 
Gerry

**Comment by andmade** [comment]
@bibliodrone 

Hi Gerry,

Yes, objects and arrays Must have their default values returned via a function. See: https://vuejs.org/v2/guide/components-props.html#Prop-Validation.

**Comment by nhillsbos** [comment]
I see. I will try this change and see how it works. I will respond later tonight. Thank you!

**Comment by audreychenjj-2019** [comment]
@nhillsbos I really like the look and feel of your game! Then I'm curious enough to click "view page source". Now I have a question. **Why I can see much much more lines of codes on your page compared to mine when clicking "view page source"?**  The few lines of codes I can see from my own page are generated by Vue CLI. I only made minor changes.

**Comment by nhillsbos** [comment]
I'm still learning a lot about these technologies, so I may have made a mistake. But I used the "comprehensive" approach, which I believe does not use the Vue CLI.

**Comment by susanBuck** [comment]
Note - the comprehensive approach *does* use the Vue CLI. Ref: https://hesweb.dev/e28/notes#/vue/build-comprehensive

I'd like to close out this thread since the original issue is resolved, but feel free to make a new post @audreychenjj-2019 if you have pending questions/concerns about the code you're seeing in View Source. 👍
